### ISSUE TITLE
dev: problem with connection maintenance (perhaps EKS specific??)

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#1021]
**What happened?**  

```
$ devspace dev
...
normal startup, log, then after a while:
...
W0318 16:30:55.188725   69529 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1001 clients constructed calling "aws-iam-authenticator"
W0318 16:30:55.188757   69529 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1002 clients constructed calling "aws-iam-authenticator"
W0318 16:30:55.188768   69529 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1003 clients constructed calling "aws-iam-authenticator"
W0318 16:30:55.188778   69529 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems
```
These messages continue "forever" though I assume eventually will cause a crash if they are meaningful.

**What did you expect to happen instead?**  

No error messages.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

... hmm... I would hypothesize this has more to do with my cluster setup. Note I do have the following sync setup for a container:
```
dev:
  sync:
  - imageName: summary
    localSubPath: ./serve
    containerPath: /app
    excludePaths:
    - __pycache__
    - /serve/summary
  - imageName: summary
    localSubPath: ./summary
    containerPath: /app/summary
    excludePaths:
    - __pycache__
```
Note that /summary is getting synced to /app/summary, which is inside of /app. I do exclude that path, though.

**Local Environment:**  
- DevSpace Version: 4.7.0
- Operating System:  mac
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

Does not seem to happen for `devspace sync` alone.

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Do you have port forwarding configured? Could you check the log files in `.devspace/logs` and see if there is any suspicious log messages especially regarding the sync or port forwarding? I suspect this might be cause via the port forwarding or restarting the sync / port-forwarding, but the sync itself shouldn't create any new clients while running and rather tries to hold on existing connections.

**Comment by shaunc** [comment]
Ah so I have running in the background --
```
39316 ttys011    0:00.29 ssh -I ... xxx.yyy.zzz.qqq -p 18664 -l root -N -L 3227:cr....
```
and also
```
30949 ttys009    0:26.54 kubectl logs -n nats-io pod/nats-streaming-cluster-1 stan --follow
```
The ssh is not actually to the EKS cluster. I don't see anything in the logs about port fowarding right now, but they are "stale" -- have been doing other things besides `dev`. Will post any info I find when I try (though now I have to get my broken build working first :)).

But ... is there some reason either of these two things might cause problems?

**Comment by FabianKramm** [comment]
@shaunc Ah, I actually meant the `dev.ports` configuration for port-forwarding, because I could imagine that this can lead to repeatedly calling the exec auth provider, however this should also appear on `kubectl port-forward` then, since its basically the same functionality. Not sure if the sync could cause this (only if it restarts often), but if it's not occuring during `devspace sync` then I think something else is causing this problem.  

Are you using the UI much, because I see in the code that the UI is recreating the client quite often. You can verify this by running `devspace dev --ui false`.

**Comment by shaunc** [comment]
I stopped and restarted `kubectl logs --follow`, and now can't generate the error anymore. I'll assume that it had to do with kubectl. (That process had been running for 4-5 days....).

Closing -- will reopen if it reoccurs. Thanks!
