### ISSUE TITLE
sync -- sync with localSubPath syncs back to wrong place and ignores exclude

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#1023]
**What happened?**  

I have an image for which I sync a local folder `./summary` to container directory `/app`. 
When run the (http) service creates `/app/out`, which I would like to sync back to the host in
the `/summary` directory. However, no matter how I configure, the contents of /app are synced back to the root context `./'. Here is the config:
```
  - imageName: summary
    localSubPath: ./serve
    containerPath: /app
    uploadExcludePaths:
    - ./serve/out
   # trying to avoid getting "/app/out/' synced to "./" on host
    downloadExcludePaths:
    - /out
    - /app/out
    - ./out
```
Trial run:
```
% ls out
ls: out: No such file or directory
% devspace sync --pod cdh-mpd-globfam-summary-74689b9876-8whn7 
[info]   Using kube context 'eks_ff-dev-crane-web'
[info]   Using namespace 'crane-web'
[info]   Start syncing                       
[done] √ Sync started on /Users/shauncutts/src/crane/crane-serverless/packages/cdh-mpd-globfam <-> . (Pod: crane-web/cdh-mpd-globfam-summary-74689b9876-8whn7)
[info]   Downstream - Download 11 files (size: 41000)
[info]   Downstream - Successfully processed 11 change(s)
^C
% ls out
bny200317famsum.csv	bny200317summary.csv	bny200318famsum.csv	bny200318summary.csv	byn200317famsum.csv
% 
```

**What did you expect to happen instead?**  

`./out` not to exist. At least one of the above sync paths should work. [**NB** the documentation should say whether the `downloadExcludePaths` are relative to `localSubPath` or to `containerPath` -- either way something isn't working.]

**How can we reproduce the bug?** (as minimally and precisely as possible)  

I believe any container will do for which there is a subdirectory and `localSubPath` and `containerPath` are set and (perhaps) point to different directories.

**Local Environment:**  
- DevSpace Version: 4.7.0
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
Have you tried to specify the flag `--config=path/to/devspace.yaml` for `devspace sync`?

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! As @LukasGentele has pointed out, `devspace sync` is ignoring any `devspace.yaml` as long as you don't specify it via the `--config` flag, which is probably causing your issue.

**Comment by shaunc** [comment]
Ah ... ok sorry about that! (NB -- though some commands reading config by default and others not is confusing. Perhaps in a major release you could go to --no-config for "raw sync"? I switched from dev to sync because of port forwarding issue and expected that "sync" would be a subset of "dev" with same flags.)
