### ISSUE TITLE
skip building image even when context files have changed

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#1029]
**What happened?**  
I initially build my docker image using `devspace dev` which works well.
But then if I stop my application, make some changes in my project files (files are located inside of the build context directory), then I run `devspace dev` again, but this time it does not rebuild the image, instead it tells me 
```
[info]   Skip building image 'php'
```
even though my source files have changed.
If I make an irrelevant change in the devspace.yaml file, here it will rebuild the docker image (but that's not helping).
I tried to edit existing files, create new one, and delete existing files. It never rebuilds the image

**Local Environment:**  
- Operating System: mac
- Deployment method: helm
- devspace version 4.8.0

**Kubernetes Cluster:**  
- Cloud Provider: local with docker for mac
- Kubernetes Version: 1.16

/kind bug

**Comment by LukasGentele** [comment]
Do you have a .dockerignore file which excludes certain file? DevSpace respects this file when checking if a rebuild it necessary.

**Comment by igoooor** [comment]
The files I'm changing are not part of the .dockerignore.

But indeed, your second thought about the `deploy` and `dev` then makes sense, because I'm indeed using `dev` with sync files defined.
But I think the workflow then is not really clear, because think about the following scenario:
1. start your environment with `devspace dev` including file sync
1. while your environment is up and running, you make changes to files
1. those files are synced into the container by devspace sync, so far so good
1. now you stop your environment with `devspace purge`
1. and you restart it with `devspace dev`

at this point, your dockerimage built at step 1 is outdated, because files have been changed, and those changes would need a docker build.
But the second `devspace dev` on step 5 won't rebuild the image (because of your explanation), and therefore you now have a running environment which is not reflecting the real state of your files.

How could one solve this issue? Of course one could use the --force-build option, but I would have thought the skip/not skipping would handle the file changes.

**Comment by LukasGentele** [comment]
Makes sense but after 5., the sync will kick in again and sync your files. Isn't that correct?

**Comment by igoooor** [comment]
Well here it will depend on your initialSync config, and the changes you applied to your files.
With certain configurations, the changes you did before step 5. may not happen as you would expect:

Assume you have `initialSync: preferLocal` and the following scenario:
1. start your environment with `devspace dev` including file sync
1. while your environment is up and running, you **delete** some files
1. those files are synced into the container by devspace sync, i.e. they are deleted in the container
1. now you stop your environment with `devspace purge`
1. and you restart it with `devspace dev`

Now the files you deleted are coming back to your local machine, because they are still in the docker image previously build, and the sync will sync them back, even though you deleted prior to the new `devspace dev`

I know that's a very specific use case, and maybe you intended it this way, it's up to you :)
It just happened to me and a coworker, and it took me some time to figure what happened and why those files kept coming back ^^"

**Comment by LukasGentele** [comment]
That is indeed a problematic case.

The only option to fix this is to use `initialSync: mirrorLocal`. If you need files to be downloaded, you could add multiple sync configs because `dev.sync` is an array and you could exclude certain files from the first sync setting with `initialSync: mirrorLocal` and then add these files in a second sync setting with `initialSync: preferRemote` or even `mirrorRemote`.

Would that be a solution?

**Comment by igoooor** [comment]
The problem I would have with the `initialSync: mirrorLocal` is that it would delete, on the container, files which are present on the container and missing locally, which is also not suitable.
Because in my case, the Dockerfile builds the application dependencies (php composer packages, npm packages, etc..) and therefore, the first time you start your environment, you don't have those dependencies locally since they are built by the Dockerfile.
So if you set `initialSync: mirrorLocal`, devspace would then delete those new files which have been created by the Dockerfile, right?

FYI, in the meantime I created a workaround because I'm actually using a custom wrapper for the whole devspace commands, and this wrapper (a go tool) is checking if the project files have changed, and then append the `--force-build` option to `devspace dev` when needed. But of course, this is not a workaround for everyone since it only works for me and my custom wrapper.

**Comment by LukasGentele** [comment]
Yes, mirrorLocal removes files remotely. However, you can just exclude the composer path using `sync.excludePaths`: https://devspace.sh/cli/docs/configuration/development/file-synchronization#excludepaths

Then, add another sync section to the `dev.sync` array and only add the composer path under `containerPath` and then set `initialSync: mirrorRemote|preferRemote`

This means that DevSpace uses mirrorLocal but not for the composer path. For the composer path it would use mirrorRemote or preferRemote depending on how you configure the second sync section.

Example:
```
dev:
  sync:
  - imageName: backend
    excludePaths:
    - vendor/
    initialSync: mirrorLocal
  - imageName: backend
    containerPath: vendor/
    initialSync: mirrorRemote
```

**Comment by igoooor** [comment]
Ok I see, it looks a bit hacky at first glance, but I will give it a try!
I will probably do this tomorrow (it's 10:30pm here).
Thanks for the big help already! I will let you know the outcome.

**Comment by igoooor** [comment]
Do you know what would be the impact of performances or cpu usage of having the sync setup you described above compared to a single sync section?

**Comment by LukasGentele** [comment]
Performance impact should be rather low. The error you saw is an issue we should definitely fix! DevSpace should be able to create this folder if it does not exist. Feel free to open a separate issue for this. Should be a very easy fix.

As a workaround for now: Either use a hook to create the folder or add a .keep file into the folder and just check this file into your git repository, so that the folder will always exist.

**Comment by igoooor** [comment]
I guess you can close this issue given that you provide a working solution to the initial problem.

**Comment by igoooor** [comment]
So the solution you provide with the two sync works (as long as the directory is present locally at the moment).
I think instead of this, I will just stop using `devspace dev` and instead split it like this:
```
devspace build
devspace deploy
devspace dev --skip-pipeline
```

Which results in the same deployment & sync, but will rebuild the docker images if the files have changed, ignoring the sync config.

**Comment by igoooor** [comment]
I think there is enough information here now on how to work around this "problem", I will close the issue.
