### ISSUE TITLE
Git clone for dependencies default to be more specific

### ISSUE THREAD

**Issue by DylanSD** [devspace-cloud/devspace#1033]
**Which solution do you suggest?**  
git clone for dependencies should default to being more specific (if not already done in the devspace CLI binary) for example specify a depth "--depth 1" when git cloning or 

You can also use git shallow clone to access a single branch:

git clone [remote-url] --branch [name] --single-branch [folder]
 
With git shallow clone you get fewer files. And as a result, they clone faster. Builds and feedback can be delivered quicker.

/kind feature

**Comment by FabianKramm** [comment]
@DylanSD thanks for opening this issue! Makes sense, I'll implement that

**Comment by FabianKramm** [comment]
Implemented in v4.9.0
