### ISSUE TITLE
.env file for secrets

### ISSUE THREAD

**Issue by 0x77dev** [devspace-cloud/devspace#1035]
**Is your feature request related to a problem?**  
No.

**Which solution do you suggest?**  
Store secrets in .env file.

**Which alternative solutions exist?**  
or some yaml file.

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
Have you tried variables in devspace.yaml yet? https://devspace.sh/cli/docs/configuration/variables/basics

They are either read from environment variables or from user input. In case of user input, they are actually stored in .devspace/generated.yaml. You can also set them before deployment using this command: devspace set var https://devspace.sh/cli/docs/commands/devspace_set_var

Let me know if that helps you to do what you're trying to achieve.

**Comment by LukasGentele** [comment]
@0x77dev Were you able to solve this using config variables?

**Comment by LukasGentele** [comment]
Closing this for now. Feel free to reopen if there are any unresolved issues.
