### ISSUE TITLE
Seamless Azure Container Registry login

### ISSUE THREAD

**Issue by kinzleb** [devspace-cloud/devspace#1037]
**Is your feature request related to a problem?**  
Currently it seems like using 'docker login' is the only way to authenticate with an image registry from ACR.

**Which solution do you suggest?**  
ACR allows authentication by using 'az acr login' and if devspace worked with the token generated from this command then users of Azure Container Registy could use the best practice approach of authenticating.

**Which alternative solutions exist?**  
Currently ACR can generate a token that works with `docker login` for you which works but is only in preview and is inconvenient.

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
Thanks for opening this issue. That's interesting. After running `az acr login`, you are able to run `docker push/pull` but DevSpace is not able to push/pull using your ACR repos?

**Comment by LukasGentele** [comment]
@kinzleb So, I took a look at the Azure docs. Is your problem that `devspace deploy/dev` works but you always need to run `az acr login` beforehand because the Azure token expires every 3h?

**Comment by kinzleb** [comment]
Hi @LukasGentele 

> Thanks for opening this issue. That's interesting. After running az acr login, you are able to run docker push/pull but DevSpace is not able to push/pull using your ACR repos?
Yes, this is my experience,

> @kinzleb So, I took a look at the Azure docs. Is your problem that devspace deploy/dev works but you always need to run az acr login beforehand because the Azure token expires every 3h?
No, I tried always doing a fresh `az acr login` before running devspace deploy/dev and would receive authentication error with the registry.

I wonder if it is related to the operating system.  I'm on a mac, and am using the defaults for where credentials are stored.

**Comment by kinzleb** [comment]
@LukasGentele I'm not sure what 'az acr login' is actually doing under the hood, but if I look at `~/.docker/config.json` on my system I see:
`{
        "auths": {
                "myacrregistryname.azurecr.io": {}
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.5 (darwin)"
        },
        "credsStore": "desktop",
        "stackOrchestrator": "swarm"
}`

But when I run `docker system info` I don't see anything about my ACR registry, I still see `Registry: https://index.docker.io/v1/` -- but that doesn't change even after I do `docker login` so I'm not sure where the difference lies in how `az acr login` works versus `docker login`.

**Comment by LukasGentele** [comment]
Not very clear to me either what the Azure CLI is doing here.. we are interacting directly with the Docker credential helper (which Docker should also be using and Azure maybe also?). So, unclear to me.

We need to investigate this. As an alternative solution: You could create a Service Principle as described here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#create-a-service-principal

Then use the Principle ID (=username) and password to login via `docker login`. That should definitely work.

**Comment by LukasGentele** [comment]
PS: A service principal might actually be the recommended way because these credentials do not expire. The token generated by the azure login expires after 3h, so when running inside a Kubernetes cluster as pull secret, it could create problems when Kubernetes reschedules or restarts the pod because is is not clear if the image can still be pulled. With a service principal, this cannot happen.

**Comment by kinzleb** [comment]
Thanks for looking into this.  I found the workaround I'm using to work alright using `az acr token create` to generate a unique token per developer they store here `.devspace/docker-token` and then allowing them to use `cat .devspace/docker-token | docker login --username $TOKEN_NAME --password-stdin myacrregistryname.azurecr.io`.

This way we can still control access each developer's token has and audit who did what.  But dealing with the tokens is less convenient.

**Comment by kinzleb** [comment]
> PS: A service principal might actually be the recommended way because these credentials do not expire. The token generated by the azure login expires after 3h, so when running inside a Kubernetes cluster as pull secret, it could create problems when Kubernetes reschedules or restarts the pod because is is not clear if the image can still be pulled. With a service principal, this cannot happen.

With `az acr token create` I can set the tokens to never expire.  These are only being used by developers to push/pull images -- the AKS Kubernetes cluster they all develop on is configured with the ACR registry to be able to push/pull without an issue there.

**Comment by LukasGentele** [comment]
Okay, great. Thanks for clarifying and for explaining this approach. That seems even easier than the service principal. 

One additional suggestion: If developers have the permission to run the command `az acr token create`, you could also automate the token generation and docker login using hooks: https://devspace.sh/cli/docs/configuration/hooks/basics - if you decide to do this, make sure to write a script which generates .devspace/docker-token and logs into docker only if this file does not exist, otherwise you'd end up with millions of tokens.

**Comment by kinzleb** [comment]
That's actually exactly what I'm doing :)  I was leaving out some detail earlier.  For some more detail, the main pain point I've found with this approach using `az acr token create` is that it requires specifying all of the repository permissions individually -- I don't see a way to permission ALL repositories in the registry or wildcard matching at this point (I know that is an Azure issue, and like I said in the beginning, this is still a preview feature for them).  So when a developer creates a new image repository they have to delete their old token (both the file on their system and from azure) and update the script that generates the token to include the permission for the new repository.

**Comment by LukasGentele** [comment]
Awesome. Well, I'll close this for now and might steal your idea later on to extend the docs regarding this solution. For now, I think there is plenty of info in this thread for others to find. Thanks for the detailed explanations especially regarding the Azure-specific limitations!
