### ISSUE TITLE
devspace requires yarn

### ISSUE THREAD

**Issue by jmcantrell** [devspace-cloud/devspace#1044]
**What happened?**  
I installed the CLI via npm, and initialized a project.

**What did you expect to happen instead?**  
What is described in the "getting started" documentation.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
npm uninstall yarn
npm install devspace
npx devspace init
```

**Local Environment:**  
- DevSpace Version: unable to run version command
- Operating System: mac

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version:
```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
@jmcantrell I'm not 100% sure what you mean. You should install DevSpace using the `-g` flag for npm. So, `npm install -g devspace` is not working for you unless you install yarn first?

**Comment by jmcantrell** [comment]
It does appear to work when installed globally. Do you know why it can't be installed locally and run using `npx devspace` or `./node_modules/devspace/.bin/devspace`?

**Comment by LukasGentele** [comment]
You are right, the npm installer needed some refactoring and npx was also not possible so far. I fixes this in this PR: https://github.com/devspace-cloud/devspace/pull/1055 - once the next version will be released, npm/yarn/npx will work much better (including non-global installations).

One note: For non-global installs, the actual devspace binary will still be downloaded to the global module directory (either yarn or npm) and then referenced from the local node_modules folder. Uninstalling devspace via yarn or npm will also clean up the globally stored binary.
