### ISSUE TITLE
problem installing Devspace on Mac.  get `Cannot find module '/usr/local/index.js'`

### ISSUE THREAD

**Issue by anuaimi** [devspace-cloud/devspace#1062]
**What happened?**  
- installed DevSpace. Seemed to complete successfully.  But then when I typed 'devspace help', it showed an error (Error: Cannot find module '/usr/local/index.js') and then started displaying 'Finishing installation for DevSpace CLI' again and again. This happens if I type 'devspace version' as well.

```
➜  learn_k8s npm install -g devspace
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/devspace -> /usr/local/lib/node_modules/devspace/bin/devspace

> devspace@4.11.0 postinstall /usr/local/lib/node_modules/devspace
> node index.js install

+ devspace@4.11.0
added 94 packages from 94 contributors in 12.995s
➜  learn_k8s devspace help
Finishing installation for DevSpace CLI
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/usr/local/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Finishing installation for DevSpace CLI
Finishing installation for DevSpace CLI
Finishing installation for DevSpace CLI
Finishing installation for DevSpace CLI
Finishing installation for DevSpace CLI
```

**What did you expect to happen instead?**  
- show help message

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
  can't tell as g
- Operating System: windows | linux | Mac
Mac 10.15.4. Node v13.12.0
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
@anuaimi Thanks for reporting this. I fixed the issue and released a new version.
