### ISSUE TITLE
Using integer or boolean string vars in env does not convert to string

### ISSUE THREAD

**Issue by rosen91** [devspace-cloud/devspace#1069]
**What happened?**  
Defining an integer or boolean variable using the following syntax
- name: GATEWAY_MAIL_PORT
source: env
default: "2525"

And referencing it in the env part
 - name: MAIL_PORT
                value: "${GATEWAY_MAIL_PORT}"

Gives the following error
cannot patch "api-gateway" with kind Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 2, error found in #10 byte of ...|,"value":2525}

devspace render gives the following output
- name: MAIL_PORT
value: 2525

**What did you expect to happen instead?**  
That the variable would be converted and inserted as a string
devspace render should output
- name: MAIL_PORT
value: "2525"

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: 4.11.1
- Operating System:  mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: 1.15

**Anything else we need to know?**  
Seems to be a common error, and solved via help pipe quote
[https://helm.sh/docs/howto/charts_tips_and_tricks/#quote-strings-dont-quote-integers](https://helm.sh/docs/howto/charts_tips_and_tricks/#quote-strings-dont-quote-integers)

/kind bug

**Comment by FabianKramm** [comment]
@rosen91 thanks for reporting this issue! Yes seems like a bug, I'll fix this as soon as possible

**Comment by shaunc** [comment]
Seems that this has regressed in devspace version 6.1.1?

I have in container env: 

```yaml
- name: MAX_SEND_INTERVAL
  value: "${MAX_SEND_INTERVAL}"
```

And in vars: 
```yaml
  MAX_SEND_INTERVAL:
    source: env
```

Render shows me:
```yaml
            - name: MAX_SEND_INTERVAL
              value: 600
```
which does not deploy.

**Comment by lizardruss** [comment]
@shaunc  It looks like the original fix was to add the option to force a string using `$!{MAX_SEND_INTERVAL}`. Can you try that and report back?
