### ISSUE TITLE
nodeSelector and tolerations config for Component Chart

### ISSUE THREAD

**Issue by devscipline** [devspace-cloud/devspace#1088]
**Is your feature request related to a problem?**  
Can't set nodeSelector and tolerations properties when using Component Chart

**Which solution do you suggest?**  
Add the ability to set nodeSelector and tolerations properties when using Component Chart

**Which alternative solutions exist?**  
It seems to me that it's not currently possible when using Component Chart. So I need to deploy using another method (regular manifests for ex)

/kind feature

**Comment by LukasGentele** [comment]
@devscipline Thanks for requesting this feature. Should be easy to add.

**Comment by devscipline** [comment]
@LukasGentele Thank you ! Is it possible to also add the strategy property ?
