### ISSUE TITLE
Devspace UI freezes the CLI tool

### ISSUE THREAD

**Issue by BirknerAlex** [devspace-cloud/devspace#1101]
**What happened?**  
I was using devspace as usual and suddenly the tool broke and don't want to start the UI server. Which also breaks the `devspace dev` command because the CLI tool is waiting for the running UI.

I restarted the Mac already and deleted the ~/.devspace folder to be sure I have a clean setup. But still no change, the UI worked before. The port 8090 is not in use by another process.

```
........
[done] √ Port forwarding started on 8080:8080                          
[done] √ Sync started on /Users/alexander/IdeaProjects/project/backend <-> . (Pod:alex/project-api-78b6d4686c-w7jx5)
[info]   Opening 'http://localhost:8080' as soon as application will be started (timeout: 4m0s)
[wait] ⠋ Starting the ui server... (455s)
```

**What did you expect to happen instead?**  
Tool not freezing while using `devspace dev` or `devspace ui`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Don't know what to do to reproduce. Still working on finding a fix....

**Local Environment:**  
- DevSpace Version: 4.12.3
- Operating System: MacOS 10.15.4 

/kind bug

**Comment by FabianKramm** [comment]
@BirknerAlex thanks for reporting this issue! Seems like devspace is stuck either at downloading the ui or checking if the port on the local machine is available. To verify if its the first can you erase the folder `$HOME/.devspace` and after executing `devspace dev` check if the folder `$HOME/.devspace/ui` has any contents? 

You can also skip opening the ui during the `devspace dev` command with the `--ui=false` flag.

**Comment by BirknerAlex** [comment]
Yeah I thought it's a socket or download problem but It seems like the download is working. But I can not find any reason why it freezes.

```bash
alexander:~/.devspace/ui$ ls -all
total 0
drwxr-xr-x  3 alexander  staff   96 12 Mai 15:40 .
drwxr-xr-x  5 alexander  staff  160 12 Mai 15:53 ..
drwxr-xr-x  7 alexander  staff  224 12 Mai 15:40 v4.12.3
alexander:~/.devspace/ui$ du -s v4.12.3/
5968	v4.12.3/
```

Port seems to be fine (free) too:

```
alexander:~/.devspace/ui$ telnet 127.0.0.1 8090
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

```
alexander:~/.devspace/ui$ lsof -nP | grep ":8090"
alexander:~/.devspace/ui$ 
```

But i found something from interest. I used the `--server` parameter to force the startup. Now it no longer freezes while starting but always saying the port is in use. But it makes no difference which port I am using. 

````
alexander:~/IdeaProjects/sc1-mono$ devspace ui --port 9090 --server
[info]   Using kube context 'local'
[info]   Using namespace 'bm-alex'
[fatal]  Port 9090 already in use
alexander:~/IdeaProjects/sc1-mono$ devspace ui --port 8090 --server
[info]   Using kube context 'local'
[info]   Using namespace 'bm-alex'
[fatal]  Port 8090 already in use
alexander:~/IdeaProjects/sc1-mono$ devspace ui --port 19884 --server
[info]   Using kube context 'local'
[info]   Using namespace 'bm-alex'
[fatal]  Port 19884 already in use
````

**Comment by FabianKramm** [comment]
@BirknerAlex thanks for the additional information! Yes so it seems devspace is not able to listen on any ports thats why it assumes every port is already in use. Currently the check devspace does to find out if a local port is open is to try to listen on that port and if that fails it assumes the port is already in use. However it seems this check is not sufficient here because the listen fails for some other reason. I think we'll have to improve this check and print the real error message instead. I guess you can verify this with a simple:

```
import (
	"net"
	"strconv"
        "fmt"
)

// CheckHostPort if a port is available
func CheckHostPort(host string, port int) (status bool, err error) {
	// Concatenate a colon and the port
	host = host + ":" + strconv.Itoa(port)

	// Try to create a server with the port
	server, err := net.Listen("tcp", host)

	// if it fails then the port is likely taken
	if err != nil {
                fmt.Println(err)
		return false, err
	}

	// close the server
	server.Close()

	// we successfully used and closed the port
	// so it's now available to be used again
	return true, nil
}

func main() {
        CheckHostPort("localhost", 8090)
}
```
 
This little program will print the real error message why listen fails

**Comment by BirknerAlex** [comment]
Seems like Docker for Mac broke the /etc/hosts file. Never seen this before, really wondering why all other applications might run fine.

But found the issue with your small tool, thanks :) 
```
alexander:$ go run test.go 
listen tcp: lookup localhost: no such host
```

My broken hosts file:
```##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##

127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Can be closed, sorry for the interrupt. But maybe it would be better if devspace prints out not a generic error message. But in this case it was a system related issue. :(

**Comment by FabianKramm** [comment]
@BirknerAlex glad you found the issue! Yes I'll implemented a fix already that will print the above message instead of hanging indefinitely.
