### ISSUE TITLE
devspace ui should display logs even if it cannot list namespaces

### ISSUE THREAD

**Issue by nberlee** [devspace-cloud/devspace#1112]
**What happened?**  
As a devspace-cloud user using `devspace ui` when displaying logs i got presented with a
```
An unknown error occurred. We're very sorry about that
```
This is probably because the url `/api/resource?resource=namespaces&context=devspace-randomname` (context is correct) is returning a http 500, in the body:
```
request: unknown (get namespaces)
```
a `kubectl get namespaces` in the same context gives me
```
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:randomname:devspace" cannot list resource "namespaces" in API group "" at the cluster scope
```

**What did you expect to happen instead?**  
Display the logs of my running devspace containers, even if it cannot list namespaces

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Use devspace cloud, make sure you do not have additional cluster assigned other than the default devspace. Make a minimal working devspace.yaml and try to use `devspace ui`

**Local Environment:**  
- DevSpace Version: devspace version 4.12.5
- Operating System: linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud (onprem cluster)
- Kubernetes Version: v1.18.3 (client & api)

**Anything else we need to know?**  
I really like devspace :P

/kind bug

**Comment by FabianKramm** [comment]
@nberlee thanks for reporting this issue! I'll take a look at this as soon as I can!

**Comment by FabianKramm** [comment]
@nberlee I took a look at the problem and the failing request to retrieve the namespaces shouldn't be a problem usually, devspace should display only the current namespace then. I suspect the `An unknown error occurred. We're very sorry about that` is caused by something else, could you open the developer tools in chrome (Command+Option+C (Mac) or Control+Shift+C (Windows, Linux, Chrome OS)) when this error occurs and paste the error messages in here please?

**Comment by nberlee** [comment]
Hi @FabianKramm ,

Not sure what happend but it is working now and I cannot replicate it anymore. This happened for my colleague and me, but not anymore. So I am closing this issue, and it is not an issue for us anymore, and I cannot get back into the described state anymore to diagnose
