### ISSUE TITLE
devspace build missing "--dependency" flag

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#1113]
**Is your feature request related to a problem?**  

I am having trouble requiring devspace to rebuild a particular dependency.

**Which solution do you suggest?**  

Add `--depedency` flag to devspace build.

**Which alternative solutions exist?**  

Good question. As far as I can tell, `--force-build` also isn't working for dependencies.
The only option so far is that I go to a copy of the dependency's repo and rebuild there -- which means I have to manually make sure the config is appropriate.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Seems like there are two things here:
1. `--force-build` when used with `devspace dev` and `devspace deploy` should actually also force rebuilding the dependency images. Is that not working for you? I just tested it and it works for me, it is rebuilding the images if the flag is provided
2. yes a `--dependency` flag for `devspace build` is a good idea, we can do that!

**Comment by shaunc** [comment]
Force build is not working in a complex situation for me, but I don't have a reproduction. Perhaps treat this as a report for #2 -- will open a new ticket with a reproduction for #1 if it persists.

**Comment by LukasGentele** [comment]
Implemented as part of [v4.13](https://github.com/devspace-cloud/devspace/releases/tag/v4.13.0)
