### ISSUE TITLE
Search bar for pods / containers in DevSpace UI

### ISSUE THREAD

**Issue by hvt** [devspace-cloud/devspace#1133]
First of all: we just started using DevSpace, and are excited to get going and making our DX better :smile:.

**Is your feature request related to a problem?**  
Yes, when you have lots of pods running, you have to use a browser's 'find in page' to look for the right pod / container to select, 

**Which solution do you suggest?**  
Would be great to have an interactive search bar below the KubeContext and Namespace select boxes, to search in all running pods and/or containers names by directly filtering on the given search string.

**Which alternative solutions exist?**  
Using the browser's 'find in page' functionality.

/kind feature

**Comment by FabianKramm** [comment]
@hvt thanks for reporting this issue! Yes, sounds like a good idea, I'll add it to the todo list

**Comment by FabianKramm** [comment]
@hvt Implemented in v5.0.1
