### ISSUE TITLE
Kustomize binary in path is not used

### ISSUE THREAD

**Issue by Chad-R-S** [devspace-cloud/devspace#1135]
**What happened?**  

The kubectl command is used with the outdated kustomize instead of the Kustomize in my path. It seems like it doesn't use `/usr/local/bin` as a path to look for Kustomize, which is where it is for me.

**What did you expect to happen instead?**  

I expected it to use the kustomize binary from `/usr/local/bin`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Put kustomize in `/usr/local/bin` only? Then use a kustomize feature only available in that more recent version that kubectl does not  yet support (such as `envs` under `secretGenerator`).

**Local Environment:**  
- DevSpace Version: 4.14
- Operating System: mac
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: v1.18.6

/kind bug

**Comment by LukasGentele** [comment]
@Chad-R-S Thanks for opening this issue. Just to make sure: If you run `whereis kustomize`, does it find the binary?

**Comment by Chad-R-S** [comment]
> @Chad-R-S Thanks for opening this issue. Just to make sure: If you run `whereis kustomize`, does it find the binary?

No, I don't get any output from that. I'm guessing because it uses a hardcoded path list that doesn't include `/usr/local/bin`. However, running `which kustomize` does output the location: `/usr/local/bin/kustomize`. I do have that path in my `$PATH` env, which is set to the default for my mac: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

**Comment by LukasGentele** [comment]
Great. Thanks for verifying that.

**Comment by FabianKramm** [comment]
@Chad-R-S could you post the output of `kustomize version` here? Devspace internally calls `kustomize version` to see if kustomize is installed, if that command for any reason fails or returns a false output, devspace assumes kustomize is not installed and fallsback to kubectl

**Comment by Chad-R-S** [comment]
> @Chad-R-S could you post the output of `kustomize version` here? Devspace internally calls `kustomize version` to see if kustomize is installed, if that command for any reason fails or returns a false output, devspace assumes kustomize is not installed and fallsback to kubectl

I ended up digging into the code a bit before seeing your post and stumbled across the issue actually. My output from kustomize is: `'{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:15:32+01:00 GoOs:darwin GoArch:amd64}`. However, this line of code expects there to be the word `kustomize` in the output:

https://github.com/devspace-cloud/devspace/blob/0e776ca20982e8cc6683d68c9ae5e8625837f08d/pkg/devspace/deploy/deployer/kubectl/kubectl.go#L338

Maybe that was in the case in previous versions or something? Might work to use the result of `lookPath()` instead of trying to inspect the version details, or just non-empty output or something else I guess.

**Comment by FabianKramm** [comment]
@Chad-R-S yes that exactly is the problem! Seems like they changed the output of the version command again, I'll fix this then for the next release!

**Comment by FabianKramm** [comment]
Fixed with v5.0.0
