### ISSUE TITLE
expose current namespace as a pre-defined variable

### ISSUE THREAD

**Issue by khaled** [devspace-cloud/devspace#1137]
**Is your feature request related to a problem?**  
I have a chart that (sadly) wants namespace as a `value`.

Also this would be useful for `command`s that need to know the namespace (assuming it isn't the current default, e.g. if I run `devspace -n whatever`)

**Which solution do you suggest?**  

Expose a predefined variable, maybe `DEVSPACE_NAMESPACE`

**Which alternative solutions exist?**  

None that I know of!

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@khaled thanks for reporting this issue! Yes this is actually a good idea, I can implement that.

**Comment by FabianKramm** [comment]
Implemented with v5.0.0
