### ISSUE TITLE
Write synched files as a specific user ID

### ISSUE THREAD

**Issue by BirknerAlex** [devspace-cloud/devspace#1139]
**Is your feature request related to a problem?**  

When you run a go lang container inside k8s, the go modules can't be installed since all synced files belonging to root but the go process itself it's executed as normal user. 

```Running command: go run -ldflags '-X hibee.io/backend/shared/version.version=0.0.0' gateway/cmd/gateway.go
go: writing stat cache: open /opt/app-root/src/go/pkg/mod/cache/download/github.com/!vivid!cortex/ewma/@v/v1.1.1.info76138101.tmp: permission denied
gateway/pkg/http_server/vnc_proxy.go:7:2: cannot find module providing package github.com/koding/websocketproxy: import lookup disabled by -mod=readonly
	(go.mod file is read-only.)
```

You need to execute your go binary as root to solve this issue. 

Downsides:
* Security impact even on development
* Different runtime behavior in production, maybe things that break in production like binding to ports under 1024. 

**Which solution do you suggest?**  

* Add new  `uid` setting to the devspace.yml config under `sync` (default 0  = root)
* Write all synced files as specific user instead of root
  * Maybe use https://man7.org/linux/man-pages/man2/setfsuid.2.html + https://golang.org/pkg/runtime/#LockOSThread instead doing a chown

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
Could you use this in your devspace.yaml to solve this issue?
```
images:
  some-image:
    appendDockerfileInstructions:
    - USER root
```
This effectively adds `USER root` statement to your Dockerfile (not persistent, only in-memory during the build process) which leads to executing the container as root user during development. More info about this config option here: https://devspace.sh/cli/docs/configuration/images/append-dockerfile-instructions

For CI/CD, staging or prod deployment, just create a `profile` in devspace.yaml which removes the entire `appendDockerfileInstructions` array. More info here: https://devspace.sh/cli/docs/configuration/profiles/basics

**Comment by mnpenner** [comment]
`chown` (user + group) and `chmod` options would be great.

I don't think messing with the Dockerfile is a good solution.

I'm working on Windows, so my permissions are getting messed up constantly. I have scripts to fix them but syncing overwrites them. rsync has `--chown` and `--chmod` which are awesome. Rsync takes it a step further and lets me specify different file and dir modes like `F440,D550` but chmod syntax like `a=,ug=rX` is sufficient too.

**Comment by FabianKramm** [comment]
@mnpenner for this use case devspace supports the `dev.sync.*.onUpload.execRemote` where you can define your own chown and chmod or any other arbitrary commands that will be executed for each uploaded file or folder
