### ISSUE TITLE
Devspace cannot find target in the Dockerfile

### ISSUE THREAD

**Issue by tyomo4ka** [devspace-cloud/devspace#1153]
**What happened?**  

Given a Dockerfile with 3 stages: base_build[0], prod_build[1] (FROM base_build) and  dev[2] (FROM base_build).
When I specify `prod_build` and `dev_build` as target in `devspace.yaml` config. I receive this error:

`[fatal]  build images: Error during image build: Coulnd't find target 'prod_build' in dockerfile`

Specifying `base_build` as target would work correct though.

The docker-compose can build all three targets in the same `Dockerfile` with no issues.

**What did you expect to happen instead?**  

DevSpace would be able to build the correct target in Dockerfile.

**How can we reproduce the bug?**

Use this example `Dockerfile`.

```
FROM python:3.8.3-slim-buster AS base_build

ARG APP_ENV

ENV APP_ENV=${APP_ENV}

CMD ["python", "--version"]

# PROD 
FROM base_build AS prod_build

RUN groupadd -r app && useradd -d /app -r -g app app
USER app

# DEV
FROM base_build AS dev_build

USER root
```

It could be easily built with docker:

`docker build -t test/devspace-issue --target prod_build`

but Devspace fails with the errors when this target is specified in the `devspace.yaml`:
 
```
images:
  app:
    build:
      docker:
        options:
          target: dev_build
```

**Local Environment:**  
- DevSpace Version: devspace version 5.0.0 (the 4 version had the same issue)
- Operating System: mac

/kind bug

**Comment by ChadSikorra** [comment]
I was just about to report this same issue. Though perhaps your case is slightly different from mine. It also fails to find the target when the `FROM` statement contains a buildarg, such as:

`FROM nginx:${NGINX_VERSION}-alpine as web`

If I remove the buildarg, it works fine.

**Comment by LukasGentele** [comment]
Thanks for reporting this. This issue is related to a regex that did not allows characters such as `_` and `$` in-between FROM and AS. I just pushed a fix for this.

**Comment by tyomo4ka** [comment]
@LukasGentele Thanks for fixing that so quick.

**Comment by FabianKramm** [comment]
Fixed in v5.0.1

**Comment by Chad-R-S** [comment]
@FabianKramm Was this accidentally missed? Seems like the PR is still open: https://github.com/devspace-cloud/devspace/pull/1154

When I updated to 5.0.1, I still get the error message about the target not being found. Seems like the old regex is still being used in master.

**Comment by FabianKramm** [comment]
@ChadSikorra ups, you are right, seems the PR slipped through, I made a new release v5.0.2 for this
