### ISSUE TITLE
Support access devspace UI from outside an VM (virtualbox)

### ISSUE THREAD

**Issue by DanielGlaas** [devspace-cloud/devspace#1163]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
I would like to be able to open the devspace UI in the browser running on the host machine while devspace is running in a virtual machine. Therefore a route is needed going from the host to devspace on the VM, which is mostly done by configuring static port forwarding rules in virtualbox. For this, it is necessary that the UI can also be bound to a fixed IP and not only to localhost. A setting for changing the port number already exists.
It would also be nice if this setting could be added into the devspace.yml.

**Which alternative solutions exist?**  
Opening an ssh connection into the virtual machine with the additional parameters "-L 8099:localhost:8090" enables to open the page [localhost:8099](localhost:8099) on the host, but this is very unintuitive.

**Additional context**  
Please see [this example](https://github.com/DanielGlaas/technologyconsulting-containerexcerciseapp) in my github repository where I have set up the creation of three virtual machines with vagrant and ansible, creating a nearly full working kubernetes cluster and for which the final state is now to have devspace working out of the box.

/kind feature

**Comment by FabianKramm** [comment]
@DanielGlaas thanks for reporting this issue! Yes, sounds like a good idea, we can add this setting

**Comment by FabianKramm** [comment]
@DanielGlaas this should work now in v5.0.3

**Comment by DanielGlaas** [comment]
Very nice, running `devspace ui --host a.b.c.d --port xyz` works like a charm! Its great that you implement this within one week!

Is it also possible to specify the default parameters for host and ports somewhere in the config files?

**Comment by FabianKramm** [comment]
@DanielGlaas yes its possible, however not through the config itself. Rather you'll have to create a .env file and add an environment variable which specifies this as default flag. You can checkout https://devspace.sh/cli/docs/configuration/env-file for more information

**Comment by DanielGlaas** [comment]
Yes, creating a .env file with "DEVSPACE_UI_FLAGS=--host a.b.c.d --port xyz" works very nice.

One final question:
In the docs for the .env file this is written in [Precedence](https://devspace.sh/cli/docs/configuration/env-file#precedence):
> Variables defined in your .env file take precende over the default values defined for config variables (configured in the vars section of devspace.yaml).

My interpretation was that I also could add this variable - instead defining it in the .env file - in the vars section of devspace.yml. I created the variable DEVSPACE_UI_FLAGS there but that had no effect. Also creating other variables have no effect and are not listed by `devspace list vars` until they are really used somewhere in the config.

I assume this is the intended behaviour?
I only figured this out by try & error, but not by reading the manual. Maybe the page [vars-->Basics](https://devspace.sh/cli/docs/configuration/variables/basics) could be extended to explain this explicitly.

**Comment by LukasGentele** [comment]
@DanielGlaas Yes, that is indeed intended behavior. The execution order is: 
1. get env vars from environment (.env + regular env vars) 
2. start command execution 
3. parse command args/flags
4. load config (including config vars)
5. run command functionality

That is pretty much how all cli frameworks are executing things. So because command args/flags are parsed (3) before the config can even be loaded (3), the vars in the config cannot have any impact on the command args/flags. However, for any other env vars, the config can be used as well as .env as well as env vars in your terminal.

**Comment by DanielGlaas** [comment]
Ok, thanks for this clarification.
I'm not aware of cli frameworks in principle, so maybe it is just a lack of my personal experience that I asked this question.
