### ISSUE TITLE
Unable to use DEVSPACE_GIT_COMMIT from config in subPath

### ISSUE THREAD

**Issue by keithwoody** [devspace-cloud/devspace#1165]
**What happened?**  
While configuring a repo with multiple subprojects we were unable to use the built in config variable `${DEVSPACE_GIT_COMMIT}` in our image tags due to a fatal error.
```
[fatal]  No git repository found (git open: repository does not exist), but predefined var DEVSPACE_GIT_COMMIT is used
```
This occurs both when deploying _directly from the repo_ or using the repo as _git sourced dependency_ in a different config.

**What did you expect to happen instead?**  
It should be a valid configuration given that the native git client can return the current commit from the subpath.
```
➜ git rev-parse --short=8 HEAD
1bb19758
```
vs.
```
➜ devspace print
[warn]   There is a newer version of DevSpace: v5.0.2. Run `devspace upgrade` to upgrade to the newest version.

[fatal]  No git repository found (git open: repository does not exist), but predefined var DEVSPACE_GIT_COMMIT is used
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. create a `devspace.yaml` in a subdirectory of a git repo (something that doesn't have it's own .git directory, i.e. not a submodule)
2. add a `${DEVSPACE_GIT_COMMIT}` section to images[0].tags 
3. attempt a devspace command that renders the config i.e. `devspace print` or `devspace deploy`

**Local Environment:**  
- DevSpace Version: devspace version **4.14.0**
- Operating System: **mac (10.15.6)**
- Deployment method: **helm** 

**Kubernetes Cluster:**  
- Cloud Provider: **aws**
- Kubernetes Version: 
   ```
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", 
   GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", 
   GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
   Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", 
   GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", 
   GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
   ```

**Anything else we need to know?**  
Spoke with Lukas via devspace cloud support chat and he asked me to report the issue.

/kind bug

**Comment by FabianKramm** [comment]
@keithwoody thanks for opening this issue! Yes devspace currently calculates the DEVSPACE_GIT_COMMIT variable at the dependency path, which leads to this error message. I think we can change this, since other variables are also taken from the base config.

**Comment by FabianKramm** [comment]
@keithwoody should work now with v5.0.3
