### ISSUE TITLE
Make ports configurable for devspace open

### ISSUE THREAD

**Issue by iSeiryu** [devspace-cloud/devspace#1166]
**Is your feature request related to a problem?**  
The current ```devspace open``` command hardcodes port **8080** for port-forwarding. This port is used by some other tools which causes issues.

**Which solution do you suggest?**  
Add ```-p```, ```--port``` flag to that command to provide an override.
```devspace open --port 9000```
```devspace open --port 9000:80```

**Which alternative solutions exist?**  
I can start port-forwarding with ```kubectl``` manually but it is not desired.

/kind feature

**Comment by FabianKramm** [comment]
@iSeiryu thanks for opening this issue! Yes we can add this flag, however usually devspace would try other ports if 8080 is already listened to, so maybe the check is not working there. But adding a flag for this is a good idea nonetheless

**Comment by iSeiryu** [comment]
@FabianKramm the problem happens when I run ```devspace open``` from WSL and try to access the application from Windows.

**Comment by FabianKramm** [comment]
@DanielGlaas this should work now in v5.0.3
