### ISSUE TITLE
forward statefulset pod is bad dns??

### ISSUE THREAD

**Issue by herozabbix** [devspace-cloud/devspace#1178]
**What happened?**  
I use forward on statefulset pod 9092,
/etc/host set 127.0.0.1
telnet 127.0.0.1 9092 is ok.
But when start program resolves is pod ip 10.42.xx.xx，so program connect is bad.
How should I do ?

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@herozabbix thanks for opening this issue! I'm not entirely sure what you mean by "program connect is bad". How do you establish the port-forwarding? Where does it resolve the pod ip to 10.42.xx.xx, within the container or on your local machine?

**Comment by herozabbix** [comment]
the following is my devspace.yaml:
......
  - labelSelector:
      statefulset.kubernetes.io/pod-name: mastergo-kafka-0
    forward:
    - port: 9092
      remotePort: 9092
......

Then I set /etc/hosts: 127.0.0.1 kakfa
I use telnet kafka connect is ok，like telnet kafka 9092
But I use program connect kafka is bad，program exception connect kafka resolved pod ip，my program connect other deployment forward app is ok

**Comment by FabianKramm** [comment]
@herozabbix thanks for the explanation. I'm don't think this is a devspace problem and rather a problem with port forwarding in general. Does `kubectl port-forward` work if you use it instead of devspace?

**Comment by herozabbix** [comment]
> @herozabbix thanks for the explanation. I'm don't think this is a devspace problem and rather a problem with port forwarding in general (since we are just doing a normal `kubectl port-forward` in the background). Does `kubectl port-forward` work if you use it instead of devspace?
