### ISSUE TITLE
sync ignore uploadExcludePaths and excludePaths dir

### ISSUE THREAD

**Issue by borgez** [devspace-cloud/devspace#1184]
**What happened?**  
devspace sync --verbose: 
[info]   Upstream - Upload File /.git/objects/dd/2928762a134c491e5d00b05c3cdc77326c7bd9

**What did you expect to happen instead?**  
nothing

**How can we reproduce the bug?** (as minimally and precisely as possible)  
version: v1beta9
images:
  quest-app:
    image: app/quest-app
    dockerfile: ./src/bots/quest-app/Dockerfile
    context: ./src
    preferSyncOverRebuild: true
    appendDockerfileInstructions:
      - USER root
    entrypoint:
      - dotnet
      - watch
      - run
    build:
      docker:
        useBuildKit: true
        skipPush: true
        options:
          target: build-env
deployments:
  - name: quest-app
    helm:
      componentChart: true
      values:
        containers:
          - image: app/quest-app
dev:
  sync:
    - imageName: quest-app
      localSubPath: ./src
      containerPath: /src
      excludePaths:
        - .git/
      uploadExcludePaths:
        - .git/
      onUpload:
        restartContainer: false

**Local Environment:**  
- DevSpace Version: devspace version 5.0.3
- Operating System: windows
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: docker-desktop
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@borgez thanks for reporting the issue! The problem is that you are running `devspace sync` without specifying a devspace config, you have to use `devspace sync --config devspace.yaml` to the config you have specified.

**Comment by borgez** [comment]
> @borgez thanks for reporting the issue! The problem is that you are running `devspace sync` without specifying a devspace config, you have to use `devspace sync --config devspace.yaml` to the config you have specified, then also the excludePaths are working.

i think it must use config from current folder by default
