### ISSUE TITLE
create is a unknown command for devspace

### ISSUE THREAD

**Issue by suzaku** [devspace-cloud/devspace#1197]
**What happened?**  

I tried to create a space with the command: `devspace create space my-app` and get the error `[fatal]  unknown command "create" for "devspace"`

**What did you expect to happen instead?**  

Prompted to create a account for devspace.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
devspace create space my-app

**Local Environment:**  
- DevSpace Version: devspace version 5.1.2
- Operating System: mac
- Deployment method: I don't know, just following the quickstart-golang tutorial

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud
- Kubernetes Version: 

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
`devspace create` is not part of devspace. You probably need to install the [loft plugin](https://github.com/loft-sh/loft-devspace-plugin) that will add this command to devspace.

**Comment by suzaku** [comment]
I think this should be documented in the README

**Comment by FabianKramm** [comment]
@suzaku it is documented in the README, take a look at the "Loft.sh Plugin for Easy Namespace & Virtual Cluster Provisioning" section

**Comment by suzaku** [comment]
OK, I see. The section is hidden by default so I didn't read it before I reach the choose cluster section. When I first saw this error, it seemed like I had downloaded an older version than the one being described by the document.
