### ISSUE TITLE
Disable devspace new version warning

### ISSUE THREAD

**Issue by anvouk** [devspace-cloud/devspace#1198]
**Is your feature request related to a problem?**  
yes

**Which solution do you suggest?**  
add an env/flag or something to disable the upgrade message warning or just disable it by default.

**Which alternative solutions exist?**  
None

**Additional context**  
I'd like to use a specific version of devspace and stick with it for a while. No need to get a reminder every time to update.

```[warn]   There is a newer version of DevSpace: v5.1.2. Run `devspace upgrade` to upgrade to the newest version.```

/kind feature

**Comment by FabianKramm** [comment]
@anvouk thanks for reporting this issue! Yes that sounds actually useful, we could add an environment variable with which you can turn that off

**Comment by FabianKramm** [comment]
@anvouk this is now implemented in v5.2.0 and setting the environment variable `DEVSPACE_SKIP_VERSION_CHECK` to true will prevent devspace to check for new versions
