### ISSUE TITLE
Multiple profile parents

### ISSUE THREAD

**Issue by FabianKramm** [devspace-cloud/devspace#1199]
**Is your feature request related to a problem?**  
Currently it is not easily possible to divide the devspace config into multiple composable chunks. 

**Which solution do you suggest?**  
Add a new config field `profiles.*.parents` which is an array that defines what parent profiles should be applied in what order

**Comment by LukasGentele** [comment]
New config field or rename parent to parents? I think 2 config options would be pretty confusing

**Comment by FabianKramm** [comment]
Implemented with v5.2.0
