### ISSUE TITLE
Adding helm --history-max support

### ISSUE THREAD

**Issue by BirknerAlex** [devspace-cloud/devspace#1201]
**Is your feature request related to a problem?**  
I'm using a helm chart in my devspace setup and currently devspace creates multiple helm revisions in the kubernetes secrets. This causes that the Rancher UI gets slower from time to time. 

Helm does have a CLI setting `--history-max` which limits the maximum number of revisions saved per release.

It seems devspace does not even use 10 (the default), it seems to be set to 0 / unlimited. Currently I am having more than 500 stored Helm revisions on my kubernetes project. The Rancher UI `/namespacedsecrets` request has a response body of over 100MB and that's always be loaded when selecting the project in the UI. Depending on the internet connection this can really take some time, in my case the UI needs 10-20 seconds to load now.

**Which solution do you suggest?**  

Add an option to the `devspace.yml` config to set the history-max value for Helm. 

**Which alternative solutions exist?**  

**Additional context**  

Thank you! ❤️ 

/kind feature

**Comment by BirknerAlex** [comment]
I've seen there is a upcoming change which changes the SDK to the CLI.
https://github.com/devspace-cloud/devspace/commit/14156db548822ed6d96049557be1c2d8083f571c

Maybe that fixes the issue already that at least the default of 10 should work now. I can imagine that since it's currently using the SDK and go has a default of 0 on integers we might have found the reason why there is no limit at the moment.

**Comment by FabianKramm** [comment]
@BirknerAlex yes this will be fixed with the new release. Furthermore you'll be also able to override this during the upgrade command via a custom argument. The new release will be ready in the next days

**Comment by FabianKramm** [comment]
@BirknerAlex should work now with v5.2.0

**Comment by BirknerAlex** [comment]
```yaml
upgradeArgs:
  - "--history-max=5"
```

works fine, thanks!
