### ISSUE TITLE
Can't use wildcard in manifest path

### ISSUE THREAD

**Issue by chasebolt** [devspace-cloud/devspace#1203]
**What happened?**  
Trying to use a wildcard in a manifest path and devspace reports a kubectl error. Performing the kubectl command manually, I am able to run it with no error.

screenshot of the directory layout, devspace command, devspace config, and error message
https://i.imgur.com/hUmfBnk.png

**What did you expect to happen instead?**  
Use wildcards in a manifest path

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
$ tree .k8s/kustomize
 .k8s/kustomize
├── client1
│   ├── certificate.yaml
│   ├── deployment.yaml
│   ├── env
│   ├── externaldns.yaml
│   ├── ingressroute.yaml
│   └── kustomization.yaml

version: v1beta7
deployments:
  - name: app
    kubectl:
      kustomize: true
      manifests:
        - .k8s/kustomize/*
```

**Local Environment:**  
- DevSpace Version: 5.1.2
- Operating System: linux
- Deployment method: kubectl apply -k

**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: 1.16.9

**Anything else we need to know?**  

/kind bug

**Comment by chasebolt** [comment]
fwiw ive tried single and double quotes on the manifest path. the kubectl error leads me to believe that the * is dropped somewhere between the devspace config and the kubectl command.

**Comment by FabianKramm** [comment]
@chasebolt thanks for opening this issue! Did you try to leave out the wildcard completely? In the official docs the command looks like `kubectl apply -k k8s/base` and we follow that convention with the manifests paths, hence why no wildcards should be needed.

**Comment by chasebolt** [comment]
i am able to use wildcards when using kubectl apply on the cli. my guess is probably bash expansion of the wildcard. the wildcard was suggested by @LukasGentele for a case i was dealing with. since then ive worked around the issue. feel free to close - thanks.
