### ISSUE TITLE
docker cache invalidated when using --cache-from args

### ISSUE THREAD

**Issue by chasebolt** [devspace-cloud/devspace#1204]
**What happened?**  
Added `--cache-from` args to my docker build and my builds stopped using cached layers from previous runs.

**What did you expect to happen instead?**  
Not to bust my docker layer caching

**How can we reproduce the bug?** (as minimally and precisely as possible)  
comment/uncomment the docker args between runs to see the cache being invalidated
https://gist.github.com/chasebolt/04e729082197c713b2615032c86b2709

**Local Environment:**  
- DevSpace Version: 5.1.2
- Operating System: linux
- Deployment method: none

**Kubernetes Cluster:**  
- Cloud Provider: none
- Kubernetes Version: none

**Anything else we need to know?**  
n/a

/kind bug

**Comment by FabianKramm** [comment]
@chasebolt thanks for opening this issue! I don't think this is a devspace issue, if you try to run `docker build .` and `docker build . --cache-from alpine:latest` I get the same results. Devspace is not doing anything else than passing these arguments to the docker cli. If I pass any other arguments than `--cache-from` it uses cache layers as usual.

**Comment by chasebolt** [comment]
ok so this is an interesting issue as i am able to get caching to properly work when using some private images - but not with the alpine example. either way this is definitely a docker issue and i cant seem to find the exact reason for it, going to close this. thanks for looking at it!
