### ISSUE TITLE
devspace use the in-cluster config if no kube-config exists

### ISSUE THREAD

**Issue by memoryliu** [devspace-cloud/devspace#1205]
**Is your feature request related to a problem?**  
My team have some automated CI jobs in k8s, using devspace deploy k8s env. We get a error when devspace is running in pod:
_[fatal]  kube config is invalid: please make sure you have an existing valid kube config_

**Which solution do you suggest?**  
Can you please add an automatic fallback to using the in-cluster config.
if no kube-config exists, use new in-cluster config  instead because that would make things a lot easier when using devspace in CI/CD and such

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@memoryliu thanks for opening this issue! Yes I think thats possible, we can add that

**Comment by FabianKramm** [comment]
@memoryliu implemented in v5.2.1
