### ISSUE TITLE
Allow initContainer configs to set imagePullPolicy 

### ISSUE THREAD

**Issue by keithwoody** [devspace-cloud/devspace#1207]
**Is your feature request related to a problem?**  
Yes, I assumed initContainers worked exactly the same as containers and attempted to set `imagePullPolicy: Always` in a config to pull the latest prebuilt deployment image for a database initialization task. However, after setting the value, it didn't propagate to the deployment config _or_ complain that the setting was invalid and instead used an old image that was missing an update for the seeding process. This only became clear after inspecting the deployment and comparing the image SHAs.

Once I realized the imagePullPolicy seemed off, I was able to `kubect edit` the deployment, update the setting on the initContainer, delete the pod, and see it update with the correct image SHA on the next deploy.

**Which solution do you suggest?**  
Allow `initContainers` configs in deployments section to set `imagePullPolicy: Always` and propagate it to the rendered deployment config. (Don't think I'm phrasing this right, but I'm still a helm/kubernetes noob 🤷)

**Which alternative solutions exist?**  
Not sure.

**Additional context**  
@LukasGentele asked me to post this issue after bringing it up in a support chat session. 

It's a bit of an edge case as we don't often need to re-seed an environment or make changes to the seeding process, but when we do, it's important that it use the latest image. 

/kind feature

**Comment by FabianKramm** [comment]
@keithwoody thanks for reporting! Seems like an issue in the component chart to me

**Comment by FabianKramm** [comment]
@keithwoody implemented in v5.2.1
