### ISSUE TITLE
Bug: devspace not streaming logs from all the containers defined in devspace.yaml

### ISSUE THREAD

**Issue by ragnarpa** [devspace-cloud/devspace#1211]
**What happened?**  

If your Kubernetes Deployment contains multiple containers started from images
defined in devspace.yaml then `devspace dev` starts to stream logs only from one of
the containers.

**What did you expect to happen instead?**  

After a developer starts `devspace dev` then all the logs from different containers (even if they are in the same pod) should be shown in the log stream.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

https://github.com/ragnarpa/devspace-container-log-bug

**Local Environment:**  
- DevSpace Version: devspace version 5.2.0
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@ragnarpa thanks for reporting this issue! Yes currently log streaming is not supported for multiple containers in the same pod, however I think we can add this

**Comment by FabianKramm** [comment]
@ragnarpa Implemented in v5.2.1
