### ISSUE TITLE
--no-watch prevents file sync

### ISSUE THREAD

**Issue by iSeiryu** [devspace-cloud/devspace#1223]
**What happened?**  
I need to copy some files into my container once via devspace hook. I'm trying to use ```devspace sync``` command and since I only need it once I need to use ```--no-watch``` flag.

Running ```devspace sync --container-path=/home --local-path=./some-folder --no-watch``` does not work.
I tried to use ```--download-on-initial-sync=false```, ```--upload-only```, ```--initial-sync=mirrorLocal```.
All same commands with same flags work as expected if I omit ```--no-watch``` flag. But without that flag it would freeze the terminal and not let my deployment to continue.

**What did you expect to happen instead?**  
Files are copied into the pod.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
A folder with a single file on local.
A container (I'm using postgres image).
```devspace sync -l some-label=some-value --container-path=/home --local-path=./your-folder --no-watch```

**Local Environment:**  
- DevSpace Version: 5.2.2
- Operating System: windows
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@iSeiryu thanks for reporting this issue! Yes that is a bug, I'll fix that

**Comment by FabianKramm** [comment]
@iSeiryu this should be fixed with v5.4.1
