### ISSUE TITLE
--config flag: Dependency local path starts from working dir of shell

### ISSUE THREAD

**Issue by harryttd** [devspace-cloud/devspace#1226]
**What happened?**  
This is defined in a sub dir devspace file in my project:
```yaml
dependencies:
  - name: chain
    source:
      path: ../../
```

With normal devspace dev, this works just fine.

However if you decide to use `devspace dev --config foo/bar/devspace.yaml` from say the root of my project, the local path of the dependency starts from the working dir of the shell, in this case the root of the project. It does not start from where the sub devspace.yaml file is located within the project.

**What did you expect to happen instead?**  
Local path should still work by beginning its path from where it is located in the project. Not based on the working directory of the shell where you invoked the command.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.3.0
- Operating System: mac

/kind bug

**Comment by FabianKramm** [comment]
@harryttd thanks for reporting this issue! Yes this is a bug, we'll fix that!
