### ISSUE TITLE
Affinity or node selector for kaniko pod

### ISSUE THREAD

**Issue by azagarelz** [devspace-cloud/devspace#1240]
**Is your feature request related to a problem?**  
Yes, the documentation seems to suggest that we can't specify a kind of affinity for our kaniko build pods and this makes hard to force the scheduling of such pods on a set of dedicated nodes

**Which solution do you suggest?**  
Add a configuration option in case of kaniko build engine, that let people specify an affinity or at least a node selector for the kaniko pod

/kind feature

**Comment by FabianKramm** [comment]
@azagarelz thanks for opening this issue! Yes I think we can add that to the config

**Comment by FabianKramm** [comment]
@azagarelz `images.*.build.kaniko.nodeSelector` was added in v5.5.0
