### ISSUE TITLE
Failing install - WARNING: npm binary directory NOT in $PATH environment variable: /home/arthur/.npm-packages/bin

### ISSUE THREAD

**Issue by arthurlogilab** [devspace-cloud/devspace#1251]
**What happened?**  

devspace "finishing installation" in a loop. Had to Ctrl-C to stop it. 

```
$ devspace
Finishing installation of DevSpace CLI
Running: node /home/arthur/.npm-packages/bin/../lib/node_modules/devspace//index.js finish-install /home/arthur/.npm-packages/bin
(not in PATH env variable)


################################################
WARNING: npm binary directory NOT in $PATH environment variable: /home/arthur/.npm-packages/bin
################################################

Finishing installation of DevSpace CLI
Running: node /home/arthur/.npm-packages/bin/../lib/node_modules/devspace//index.js finish-install /home/arthur/.npm-packages/bin
Finishing installation of DevSpace CLI
Running: node /home/arthur/.npm-packages/bin/../lib/node_modules/devspace//index.js finish-install /home/arthur/.npm-packages/bin
^C
```

My `$PATH` contains the path (but with a trailing `/`) : 

```
PATH=/home/arthur/.rbenv/shims:/home/arthur/.rbenv/bin:/home/arthur/.cargo/bin:/home/arthur/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/arthur/bin/:/home/arthur/go/bin/:/home/arthur/.npm-packages/bin/:/home/arthur/.gem/ruby/2.5.0/bin:/home/arthur/.local/bin:/home/arthur/.krew/bin:/home/arthur/bin/:/home/arthur/.npm-packages/bin/:/home/arthur/.gem/ruby/2.5.0/bin
```

**What did you expect to happen instead?**  

To either succeed or stop after trying a few times and display an error message. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

* Ubuntu 
* `npm install -g devspace`
* `export `PATH=$PATH:$HOME/.npm-packages/bin/`
* make sure the one without the trailing `/` is not present.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.5.0
- Operating System: linux 
- Deployment method: n/a

**Kubernetes Cluster:**  
- Cloud Provider: n/a
- Kubernetes Version: n/a

**Anything else we need to know?**  

Work around : 

```
$ export PATH=$PATH:/home/arthur/.npm-packages/bin
$ devspace
```
worked 

/kind bug

**Comment by LukasGentele** [comment]
@arthurlogilab Thanks for reporting this and sorry for the late reply. I pushed a fix which will be available with the next version.
