### ISSUE TITLE
Regression: Terminal Column Width

### ISSUE THREAD

**Issue by lots0logs** [devspace-cloud/devspace#1256]
**What happened?**  
The latest update has [this issue](https://github.com/devspace-cloud/devspace/issues/1190) again.

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  
See original issue linked above

**Local Environment:**  
- DevSpace Version: 5.5.0
- Operating System: linux
- Deployment method: 

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@lots0logs thanks for reporting this issue! So for me it still works, I tested it on 2 different systems (mac and windows), since when does it not work for you anymore? Do you have any special terminal configuration locally?

**Comment by lots0logs** [comment]
Now its not doing it. I did update to the new release earlier today. Doesn't seem like it would have been fixed by the changes in the changelog so I guess it was a fluke. I'll reopen if the issue returns. Thanks.
