### ISSUE TITLE
(feat): custom labels/annotations for builder pod

### ISSUE THREAD

**Issue by lukasmrtvy** [devspace-cloud/devspace#1265]
**Is your feature request related to a problem?**  
I want to integrate solution, where developer will not need credentials to registries. It can be achieved ( in Azure ) via managed identites, service principals or pull image secrets. Thats unfortunatelly unhappy solution, at least for service principals and pull image secrets, because these must be dynamically reflected/replicated to all potentional namespaces ( that are created by devspace ). Manage identites will allow AKS cluster to integrate with ACR for pulling, pushing images, unfortunatelly this will work only for kubelet ( node identity ), not for pod itself ( builder pod ), but its possible to achieve it via https://github.com/Azure/aad-pod-identity/ . Problem is that identity is binded only to pods with specific label starting with `aadpodidentity`.

**Which solution do you suggest?**  
Would be nice to support custom labels/annotations for builder pod, this will allow aad-pod-identity to bind identity which will allow pulling/pushing images from/to ACR.

**Which alternative solutions exist?**  
- `az acr login -n myregistries` -> needs docker cli installed
- `az acr token create -n foo --registry myregistries--repository dev content/write content/read`  -> needs higher SKU of ACR

Related: https://github.com/devspace-cloud/devspace/issues/1037
**Additional context**  
no

/kind feature

**Comment by FabianKramm** [comment]
@lukasmrtvy thanks for reporting this issue! Yes we can add that!

**Comment by FabianKramm** [comment]
@lukasmrtvy this should work with v5.6.1 now!
