### ISSUE TITLE
Don't open a shell into the container until everything is synced (initially)

### ISSUE THREAD

**Issue by KaelBaldwin** [devspace-cloud/devspace#343]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?** 

A configuration option to block opening the shell into the container until the sync process is initially caught up.

**Which alternative solutions exist?**  

**Additional context**  

My project can be rather large, especially if syncing all the dependencies.
I could exclude the dependencies from syncing, but overall it saves time to go ahead and let them sync.

However, if a developer gets into the project they can't really tell when everything is synced up without looking at the sync.log file. This might lead them to go ahead run the command to install all the dependencies themselves, or other commands that won't work correctly until everything is synced.

/kind feature

**Comment by LukasGentele** [comment]
That might be a good idea to have that as a config option. Thanks for suggesting it. I would suggest an output like:
```
Initial code sync in progress (Xs) - Press ENTER to run sync in background and open terminal directly
```
That would allow users to skip the initial sync even if the config specifies the wait option. What is your opinion on this?

@FabianKramm: I think this option should not be specified in every sync path but rather in one central place to make it easier to use. Would `devspace.terminal.waitOnInitialSync: true|false` be a suitable config option?

**Comment by KaelBaldwin** [comment]
@LukasGentele Sorry, I see that I missed responding to your question. Yes I think that would be an excellent solution.

**Comment by LukasGentele** [comment]
Awesome. I think @FabianKramm will work on this within the next few days.

**Comment by KaelBaldwin** [comment]
woohoo! thanks!
