### ISSUE TITLE
Proposal: Move container side logic to a golang binary.

### ISSUE THREAD

**Issue by KaelBaldwin** [devspace-cloud/devspace#441]
**Is your feature request related to a problem?**  
Windows based containers won't work with the container side logic being in a shell script.

**Which solution do you suggest?**  
I suggest creating a new golang project (optionally titled astronaut, since it is sent out into devspace) which would handle all container side logic.

Doing this would make it possible to use either a windows or linux binary, based on the operating system of the container, while still maintaining one codebase for the logic.

Also, this could also give more control over the different container side processes than is easily accomplished via a shell script. The communication could be moved out of the kubectl exec connection into a server/port or something as well. There are a lot of possibilities that would be opened up by this.

**Which alternative solutions exist?**  
The other option would be to have an alternative script for windows containers, such as a batch script that accomplishes the same thing as the bash script on linux, if that's possible.

**Additional context**  
It should be stated that I've never actually used a windows based container, so there could be other problems I'm unaware of, but as far as I know, it should work.

/kind feature

**Comment by FabianKramm** [comment]
Implemented in v3.5.5
