### ISSUE TITLE
Hooks for executing custom scripts

### ISSUE THREAD

**Issue by FabianKramm** [devspace-cloud/devspace#535]
It can be helpful to run user-defined commands/scripts after or before certain pipeline steps. This allows more customization of the pipeline and gives the user more freedom of integrating devspace into his own pipeline or use devspace as the primary pipeline tool.

**Comment by FabianKramm** [comment]
@musicformellons for which command do you try to automatically select a pod? Usually the commands have additional flags that allow you to specify a pod and prevent a select

**Comment by musicformellons** [comment]
@FabianKramm Ah, thanks, I found the flags and now indeed can get into my containers without the select! That's nice. When I am at the prompt of my container I can no longer script anything it seems, I am trying (with tilix terminal) e.g.:
`tilix -e bash -c 'cd /myapp; devspace enter -c mycontainer -n default -l app=myapp-pod; sleep 5; cd /folder_on_my_container; $SHELL'` 
But it stops at the container prompt and does not run the `cd /folder_on_my_container`. Any suggestions?

**Comment by LukasGentele** [comment]
Hi @musicformellons! I just took a look at this script. For me, the current behavior seems correct but probably not what you intend to do with this script.

From what I see the script does the following within the tilix shell:
1. Switch to /myapp
2. Run devspace enter 
3. sleep 5 seconds
4. ....

Your issue is that 3. and the rest will never be executed. The reason for this is that 2. "devspace enter" waits for an input and 3. can never be executed until the "devspace enter" process terminates. Are you trying to run 3., 4., ... within the terminal of the container or on your local computer?

Let me know what your script is meant to do and I will probably be able to help you with this.

**Comment by musicformellons** [comment]
@LukasGentele On the terminal of the container!

**Comment by LukasGentele** [comment]
Ok, got it. If you want to run "devspace enter" and then execute something within the container terminal, you can provide it as a argument to the command. So, I would change your code like this:

```
tilix -e bash -c 'cd /myapp; devspace enter -c mycontainer -n default -l app=myapp-pod bash -c "sleep 5; cd /folder_on_my_container; $SHELL"'
```

the `bash -c "sleep 5; cd /folder_on_my_container; $SHELL"` as an argument to `devspace enter` opens the command bash just like you open tilix and passes the 3 commands sleep, cd, and $SHELL with the `-c` flag to this shell within the container. Does this work as intended? @musicformellons

**Comment by musicformellons** [comment]
Ha! I tried similar things before but gave up on it as I did not get it working, but now I got it working!! With two small adjustments to your line. Working line is:
```tilix -e bash -c 'cd /myapp; devspace enter -c mycontainer -n default -l app=myapp-pod bash -c "sleep 5; cd ./folder_on_my_container; $SHELL"; $SHELL'```

Now that I have that out of the way, my following requirement would be to have multiple of these lines, but make them synchronous. So I would like to first have one server started up using the terminal command we just got, and when that runs, have a second one start up with a similar terminal command. Any idea how to go about that?

**Comment by musicformellons** [comment]
I would think the same approach would work on the ```devspace dev``` command, but it stops and does not run the commands in the container. Any idea why?

**Comment by musicformellons** [comment]
Actually, after correcting a typo it also works with ```devspace dev``` command.

**Comment by LukasGentele** [comment]
Great! Regarding your question in "my following requirement would be to have multiple of these lines, but make them synchronous..." - you can run several tasks in parallel in the background by using "&" at the end of the line. So this would run 3 commands in parallel:
```
devspace enter ... &;
devspace enter ... &;
devspace enter ... &;
```
They run in parallel but are not necessarily synchronized. They are just run in the background. I hope that helps. I think we should not continue this discussion in the comments of this issue as this is not directly related to this issue about hooks for DevSpace CLI. Feel free to ping me on slack if you have any further questions about shell scripting.

**Comment by FabianKramm** [comment]
Is part of version v3.5.1
