### ISSUE TITLE
Switch kubectl context during "devspace connect cluster"

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#538]
**Is your feature request related to a problem?**  
When someone connects a cluster, they are asked to run "kubectl get svc nginx-ingress-controller -n devspace-cloud" to determine the loadbalancer IP. This does not work if they are in the wrong context.

**Which solution do you suggest?**  
Switching the kubectl context during "devspace connect cluster"

**Which alternative solutions exist?**  
- Users can manually switch the context but we should make things easier than that
- The command could wait until the loadbalancer IP is assigned by the cloud provider and output the IP directly to the user but this might take a long time getting the user stuck in this command which is therefore not ideal

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
Is part of v3.5.1
