### ISSUE TITLE
Private Registry

### ISSUE THREAD

**Issue by michalip** [devspace-cloud/devspace#557]
**What happened?**  
Performed docker login to private , on premises docker registry then trying to initialize devspace

**What did you expect to happen instead?**  
to succesfully allow registration to private docker registry

**How can we reproduce the bug?** (as minimally and precisely as possible)  
devspace init --reconfigure

     ____              ____
    |  _ \  _____   __/ ___| _ __   __ _  ___ ___
    | | | |/ _ \ \ / /\___ \| '_ \ / _` |/ __/ _ \
    | |_| |  __/\ V /  ___) | |_) | (_| | (_|  __/
    |____/ \___| \_/  |____/| .__/ \__,_|\___\___|
                            |_|

? Which Kubernetes cluster do you want to use?
 Use current kubectl context (no server-side component)
? Which namespace should the app run in? devspace
? How do you want to initialize this project?
 Use the Dockerfile in ./Dockerfile
? Which registry do you want to push to? ('hub.docker.com' or URL) A.B.C:5000
X Sorry, your reply was invalid: Answer has to match pattern: ^[a-zA-Z0-9\./-]{4,90}$
? Which image name do you want to push to? (A.B.C:5000/michalip/devspace)

During `devspace dev` I get the below response 

The push refers to repository [docker.io/library/devspace]
27391a3bcbd4: Preparing
e6192b5f4642: Preparing
55d28d9718f1: Preparing
f450f57e2182: Preparing
8fa3d8cf28af: Preparing
68e6f5460b61: Waiting
183481e8e1d0: Waiting
ee854b6a598a: Waiting
d2cbb69f1406: Waiting
8d267010480f: Waiting
270f934787ed: Waiting
02571d034293: Waiting
[fatal]  Error building image: Error during image build: Error during image push: denied: requested access to the resource is denied

**Local Environment:**  
- Operating System: linux 
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google K8s on premises
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

Not sure what values are expected because its not connecting to the private registry ...

/kind bug

**Comment by LukasGentele** [comment]
Hi @michalip. Thanks for reporting this issue. The problem is related to the regex we use to check if the image you enter is correct. Unfortunately, the regex does not allow : within an image name but your registry needs : to specify the port. That should be an easy fix. We will release a new version with the fix very shortly.

**Comment by michalip** [comment]
Hi Lukas, thanks for checking this. I believe it will be beneficial to others using on premises clusters too
