### ISSUE TITLE
uninstall devspace cli

### ISSUE THREAD

**Issue by devkws** [devspace-cloud/devspace#578]
**What happened?**  
unable to uninstall devspace cli on osx

**What did you expect to happen instead?**  
expected a devspace uninstall command

/kind bug

**Comment by LukasGentele** [comment]
Uninstalling DevSpace CLI is as easy as removing the binary file from your computer. You can run `whereis devspace` to see where the binary is located. If you also want to remove the global configuration, simple remove the folder `~/.devspace`

You are right, we should add this information to the docs or add a command for this. Currently, it is only possible via uninstall command when using npm. Thanks for pointing it out. I'll take care of this.
