### ISSUE TITLE
dependencies: add namespace option

### ISSUE THREAD

**Issue by FabianKramm** [devspace-cloud/devspace#605]
The current behavior is that every dependency is deployed alongside the current project within the same namespace / space. However in some situations it might be useful that some dependencies should be deployed to a different namespace, hence we should introduce an option called namespace where the user is able to configure this.

**Comment by LukasGentele** [comment]
Like the idea. Some things to discuss before implementing this:
1. Will DevSpace create the namespace automatically if it does not exist, yet? => I would definitely prefer that.
2. What about users of DevSpace Cloud where users cannot create namespaces directly via kubectl? => Should DevSpace create Spaces, instead? I believe that would be a good option. DevSpace could create Spaces with the name stated in this new `dependecy[].namespace` option. A thing to consider is that namespace in DS Cloud != Space name in most cases.

What are your thoughts on that?

**Comment by FabianKramm** [comment]
1. Yes it will create the namespace automatically, if it not already exists. The behavior is comparable to setting the config option `cluster.namespace`
2. I think this config option is intended for users that have cluster access and expect certain services in certain namespaces. An approach where DevSpace creates spaces instead is thinkable, however I think the option namespace should only stick to real kubernetes namespaces

**Comment by LukasGentele** [comment]
Makes sense. For 2, I think we clearly need to document that using this config option requires the right to create and access the specified namespace as DevSpace will not create spaces but only namespaces.
