### ISSUE TITLE
Bug: 'devspace enter' & 'devspace dev' command exit code is lost 

### ISSUE THREAD

**Issue by lizardruss** [devspace-cloud/devspace#614]
**What happened?**  
When running `devspace dev` or `devspace enter` with a command, the exit code of the command is not reflected by devspace

**What did you expect to happen instead?**  
If devspace is able to execute the command, I would expect it to exit with the same exit code as the command.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```sh
> devspace dev -- bash -c 'exit 1'
> echo $? # 0
```

**Local Environment:**  
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: [use `kubectl version`]
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
Fixed in v3.5.13
