### ISSUE TITLE
"list deployments" and potentially other commands do not resume sleeping spaces

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#621]
**What happened?**  
When a space enters sleep mode, spaces should be resumed when running a command related to the space. However, some commands do not resume the space which is not very transparent for the user.

**What did you expect to happen instead?**  
Resume spaces when running a command related to the space.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Enable sleep mode.
2. Deploy something.
3. Wait for sleep mode to kick in.
4. Run: `devspace list deployments`

**Local Environment:**  
- Operating System: any

**Kubernetes Cluster:**  
- Cloud Provider: any

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
Spaces will now be resumed during `devspace list deployments`.
