### ISSUE TITLE
Show picker for "devspace use space|provider|..."

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#640]
**Is your feature request related to a problem?**  
When a user runs `devspace use space|provider|...` without an argument stating the space|provider etc. name, the command will fail and ask the user to provide an argument.

**Which solution do you suggest?**  
Instead of terminating the command, DevSpace could provide a list of available spaces|providers|... for the respective command similar to the container selector shown for `devspace logs` or `devspace enter`

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
Implemented in v3.5.17
