### ISSUE TITLE
`devspace add port` should not set remotePort unless explicitly specified

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#642]
**Is your feature request related to a problem?**  
When running `devspace add port 35729`, the following lines will be added to the devspace.yaml:
```
    - port: 35729
      remotePort: 35729
```

**Which solution do you suggest?**  
Not adding `remotePort` unless we explicitly define it using `devspace add port 35729:XYZ`

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
Implemented in v3.5.17
