### ISSUE TITLE
Add verbose flag to devspace deploy

### ISSUE THREAD

**Issue by rmcclaincf** [devspace-cloud/devspace#664]
**Is your feature request related to a problem?**  
Problem is that devspace deploy when deploying dependencies can get hung up for a long time (building images, etc), and there is no feedback to tell you what's going on.   Can't really tell if something is hung up, or if I should just wait.   

**Which solution do you suggest?**  
Add a verbose flag to devspace deploy so that when deploying dependencies I can actually see the output of the steps as they happen (image builds, deploys, etc).

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
@rmcclaincf Thanks for suggesting this. Makes a lot of sense to me. We'll be adding a verbose flag to `devspace deploy` and `devspace dev` just as you suggested. Should be rather quick to ship this.

**Comment by LukasGentele** [comment]
Shipped with v4 as `devspace deploy|dev --verbose-dependencies`
