### ISSUE TITLE
Cluster Connect Error

### ISSUE THREAD

**Issue by iMerica** [devspace-cloud/devspace#700]
**What happened?**  
I'm seeing this while connecting a cluster:
```
[fatal]  initialize core: graphql: init service namespace: helm init: Error in command: exit status 1 => $HELM_HOME has been configured at /root/.helm.
Error: error installing: the server could not find the requested resource

```

**Kubernetes Cluster:**  
- Cloud Provider: self-hosted
- Kubernetes Version: Latest as of today.

/kind bug

**Comment by FabianKramm** [comment]
@iMerica thanks for opening this issue! Are you using kubernetes v1.16 by any chance? I think the extensions/v1beta1 was disabled there and helm cannot install tiller anymore (see https://github.com/helm/helm/issues/6374)
