### ISSUE TITLE
-s / --switch-context flag switches context but not namespace

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#714]
**What happened?**  
When using the `-s / --switch-context` flag, DevSpace tells the user it switches context and namespace but it only switches the context which is confusing.

**What did you expect to happen instead?**  
DevSpace should switch the context and then also set the default namespace of this context accordingly.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. `devspace deploy`
2. `devspace use namespace some-other-namespace`
3. `devspace deploy -s`
4. `kubectl config view --minify`

/kind bug

**Comment by FabianKramm** [comment]
Not reproducable

**Comment by LukasGentele** [comment]
I can assure you that this is reproducible with the exact steps as shown above. I agree, steps 1-3 are as expected BUT in step 4, you see that the kube-context will show `some-other-namespace` instead of the namespace used in step 1 which is not correct as `-s` tells the user that it switches context AND default namespace but it only switches the context, but not the namespace.
