### ISSUE TITLE
`devspace logs` should list pods with init containers when showing the picker

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#715]
**Is your feature request related to a problem?**  
Logs of init containers cannot be viewed using `devspace logs` unless all flags are provided explicitly which is not adding any benefit compared to plain `kubectl logs`.

**Which solution do you suggest?**  
Pods which are in the init phase should be listed within the pod picker, so they can be selected and init container should be listed in the container picker that appears after selecting the pod.

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
Implemented in v4.0.3
