### ISSUE TITLE
`devspace list contexts` and `devspace list namespaces`

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#716]
**Is your feature request related to a problem?**  
`devspace list` does not allow to list contexts or namespaces but that would be really useful (especially contexts) and it seems random that it does not exist because other objects that are used with `devspace use X` are available such as `devspace list spaces` and `devspace list providers`.

**Which solution do you suggest?**  
Implementing `devspace list contexts` and `devspace list namespaces` should be fairly easy as DevSpace already has picker showing this information during `devspace use context/provider`.

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
Implemented in v4.0.3
