### ISSUE TITLE
add command: `devspace set var VAR_NAME=VALUE`

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#728]
**Is your feature request related to a problem?**  
Currently, it is not possible to change the value of a single config var if it has been cached within generated.yaml.

**Which solution do you suggest?**  
Adding the command `devspace set var VAR_NAME=VALUE` would allow to set the value of a single config var. Having the same syntax as `export` makes sense to make it easily understandable and would even leave the option to reset a single var using `devspace set var VAR_NAME=` (comparable to expose).

**Which alternative solutions exist?**  
The only alternative currently is to use `devspace reset vars` but if there are many vars, this is not a great option for users.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
should be implemented in v4.2.0
