### ISSUE TITLE
devspace dev doesn't wait enough for port-forwarding

### ISSUE THREAD

**Issue by maksimru** [devspace-cloud/devspace#760]
**What happened?**  

[fatal]  Unable to start portforwarding: Error starting port-forwarding: Unable to list devspace pods: No pod with selector app.kubernetes.io/component=microservice-app,app.kubernetes.io/name=devspace-app in namespace playground found

actually pod exists with "ContainerCreating" status, simple restart of devspace dev may help

**What did you expect to happen instead?**  

wait up to 5 minutes (or configurable timeout), because sometimes if you have many sidecar containers simple image pulling may take a long time

**How can we reproduce the bug?** (as minimally and precisely as possible)  

add port section to devspace.yaml/dev

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

windows

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

google 

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@maksimru thanks for reporting! The current timeout is 2 minutes which seems to short for some cases, we can increase it to 10 minutes (if the pod has an issue starting devspace dev will stop anyways)

**Comment by FabianKramm** [comment]
@maksimru should be fixed in v4.2.0
