### ISSUE TITLE
helm version is outdated, does not work on k8s 1.16.x

### ISSUE THREAD

**Issue by vroad** [devspace-cloud/devspace#792]
**Is your feature request related to a problem?**  
Yes.
I can't directly use helm CLI from command line, because helm won't connect to older tiller.

```
Error: incompatible versions client[v2.16.0] server[v2.13.1]
````

Also, older version of helm does not work on k8s v1.16.x. Recently, helm 2.16.0 was released, which adds support for k8s 1.16.x.

https://github.com/helm/helm/releases/tag/v2.16.0

I can't find any documentation on which version of k8s devspace currently supports. Is this currently documented?

Desvspace currently uses 2.13.1, which was released at Mar 22: https://github.com/helm/helm/releases/tag/v2.13.1

**Which solution do you suggest?**  
Upgrade helm version that devspace is currently using.
And/or make helm version configurable, but is that possible?

I can't seem to prevent devspace from deploying tiller and install one by myself.

**Which alternative solutions exist?**  
Use older helm client to avoid errors, but this does not solve the problem of k8s v1.16.x support.

**Additional context**  
It's possible to run tiller 2.16.0 on k8s 1.15.x cluster as well.

/kind feature

**Comment by FabianKramm** [comment]
@vroad thanks for opening this issue. Actually we use internally helm version 2.15.1, but still deploy an older tiller (good catch). I will fix that in the upcoming release and update helm to 2.16
