### ISSUE TITLE
non-interactive uninstall for the npm package

### ISSUE THREAD

**Issue by dsebastien** [devspace-cloud/devspace#797]
**What happened?**  

In our Docker image, a certain steps executes npm prune and npm cache clean.
It seems that DevSpaces asks for user input, which I need to avoid in my scenario.

**What did you expect to happen instead?**  
Silent uninstall

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Check out the logs below:

```
...
Step 32/83 : RUN npm prune --production && npm cache clean --force
 ---> Running in 88b430bd85d7
...
> devspace@4.2.0-npm preuninstall node_modules/devspace
> node index.js uninstall

? Do you want to remove the global DevSpace config folder ~/.devspace? (Use arro
w keys)
❯ no 
  yes The command '/bin/sh -c npm prune --production && npm cache clean --force' returned a non-zero code: 130

```
- Operating System: linux

/kind bug

**Comment by dsebastien** [comment]
As far as I can tell, it occurs because of this: https://github.com/devspace-cloud/devspace/blob/master/dist/npm/index.js#L178

Ideally, I suppose that the package should identify that it is executed as part of a prune operation and avoid asking?

**Comment by LukasGentele** [comment]
Interesting observation. Makes sense to fix this. I would suggest to check if `process.stdout.isTTY == true` and only then, ask the question. isTTY essentially means that it is an interactive terminal. Docker builds would be non-interactive as well as most other automated scripts. The questions is: should be remove the global folder or not in this case. I guess it would be ok to remove it.

**Comment by dsebastien** [comment]
I can't really comment on the need/sense to remove it as I'm really only using devspace for the sync feature atm, so I'm biased ;-)

Thanks a lot for looking into this so quickly.

**Comment by LukasGentele** [comment]
@dsebastien makes sense. The isTTY check is already part of the newest release v4.2.1 - would be great if you could verify if the non-interactive uninstall works for your case.

**Comment by dsebastien** [comment]
@LukasGentele I've tested with 4.2.1 and it works fine now. Thank you for fixing this so quickly.
