### ISSUE TITLE
Latest release (v1beta5) not working fine with Helm v3

### ISSUE THREAD

**Issue by czelabueno** [devspace-cloud/devspace#831]
**What happened?**  
I just testing the tool with a simple quicktart nodejs today. I followed the steps of the guide but it crash in >devspace deploy showing me this error message:

[fatal]  Error deploying quickstart-nodejs: Unable to deploy helm chart: looks like "https://charts.devspace.cloud" is not a valid chart repository or cannot be reached: open /home/czela/.cache/helm/repository/jRrqUUapVIlNhjybEJLHAqP8Opo=-index.yaml: no such file or directory
Run `devspace purge -d quickstart-nodejs` and `devspace deploy` to recreate the chart

**What did you expect to happen instead?**  
Deploy my app within remote k8s

**Local Environment:**  
- Operating System: linux x86_64
- Deployment method: helm component

**Kubernetes Cluster:**  
- Cloud Provider: Azure AKS
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  
I changed the version in devspace.yaml file from v1beta5 to **v1beta4** to use previous version and it did works fine for me (but it's continue using tiller)

[info]   Skipping building image default
[done] √ Created deployment tiller-deploy in devspace-demo
[done] √ Tiller started
[done] √ Deployed helm chart (Release revision: 1)
[done] √ Successfully deployed quickstart-nodejs with helm
[done] √ Successfully deployed!

NOTE: I not helm installed

/kind bug

**Comment by FabianKramm** [comment]
@czelabueno thanks for reporting this issue! Could you try to delete the helm cache, especially the .helm and .cache/helm folders and retry with helm v3?

**Comment by LukasGentele** [comment]
@czelabueno Is this still an issue with the newest version and after clearing the helm cache?

**Comment by LukasGentele** [comment]
Closing this for now
