### ISSUE TITLE
Sync: issues with html files

### ISSUE THREAD

**Issue by dsebastien** [devspace-cloud/devspace#832]
**What happened?**  
For the development of our app, we're using the Angular CLI, which has hot reloading support. When we sync files using devspace sync into the pods, the Angular CLI sometimes fails to detect changes to HTML files.

At this point I'm still investigating, so I'm really not sure if the sync of devspace can do anything about it, but since I don't know what I don't know, I prefer to ask just in case.

Is there a signal or something that DevSpace sync could incur (or lack thereof) so that the CLI picks up all file modifications?

Do you have ideas around this?

One way that I saw might fix the issue is to enable the "polling" feature of the Angular CLI, but I'd really like to avoid it as it uses a ton of CPU cycles.

**What did you expect to happen instead?**  
I was hoping for the Angular CLI to notice all the file changes as it does when executed locally instead of within a pod towards which devspace syncs.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Execute NG CLI in a pod and synchronize file modifications using devspace sync.

**Local Environment:**  
- Operating System: linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: 1.16.2

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@dsebastien thanks for reporting this issue! I'll investigate this issue and try to reproduce it. If I understand your issue correctly the sync syncs the files correctly to the container, however the file change event seems to be not emitted and hence the angular CLI fails to detect it?

**Comment by dsebastien** [comment]
Yes, exactly.

Our Angular project is actually part of a Nrwl Nx workspace, but I don't think that it influences the issue.

To be clear, if I stop the "ng serve" command and restart it, it indeed builds the expected content.
If both "ng serve" and devspace sync are running, then:
* if I edit a .ts file, that file is correctly synchronized and ng serve detects/rebuilds within the pod
* If I edit a .html file, that file is correctly synchronized (unless I'm mistaken), but ng serve doesn't detect the modification.

If "n

**Comment by FabianKramm** [comment]
@dsebastien thanks for clarifying! I'm not sure if we can do much about this, since we just use regular file operations to write the file or overwrite the file in the container, so essentially we just do a `kubectl cp` into the container. Do you have any idea how we could solve this issue for you?

**Comment by LukasGentele** [comment]
@dsebastien Could you try to use the touch command with both files (.ts and .html) and see if the hot reloader detects the changes?

**Comment by dsebastien** [comment]
Hello @FabianKramm & @LukasGentele 

I've checked and apparently doing a simple "touch" after the changes does trigger the refresh.
Do you think it is something that DevSpace sync could do automatically (with some option?)

**Comment by FabianKramm** [comment]
@LukasGentele @dsebastien actually we already do a touch on the remote file after its synced and set the last access time to the current timestamp and the modified timestamp to the timestamp of the local file ([tar.go](https://github.com/devspace-cloud/devspace/blob/master/sync/server/tar.go#L100)), so I'm not sure why the command touch is triggering the update, but the sync itself is not. We could execute the function twice or set the modified timestamp to the current time, however I'm not sure if this would make any difference.

**Comment by LukasGentele** [comment]
@dsebastien Is this still an issue or can we close this?

**Comment by dsebastien** [comment]
Hello @LukasGentele . I haven't suffered from it in the last few days but have been working on other things. Let's close this issue for now, I don't want to be distracting for nothing. I'll ask to reopen if I stumble upon it again.

Thanks!
