### ISSUE TITLE
Devspace sync error

### ISSUE THREAD

**Issue by jersGH** [devspace-cloud/devspace#833]
**What happened?**  
-Im not sure if this is a bug, Im running devspace sync at the background in Linux env, after about a day I noticed that the local copy of the sync files are not updating. Upon checking I got the error below:

E1211 07:32:36.206114    7926 v2.go:105] EOF
[info]   Sync stopped
[error]  Sync Error on /cloud_storage/logviewer/psapp1/logs: downstream: count changes: rpc error: code = Unavailable desc = transport is closing
[error]  Fatal sync error: downstream: count changes: rpc error: code = Unavailable desc = transport is closing. For more information check .devspace/logs/sync.log

**What did you expect to happen instead?**  
-expect to have continuous syncing of files

**How can we reproduce the bug?** (as minimally and precisely as possible)  
-Im using this format >> devspace sync --no-watch --download-on-initial-sync --pod=<mypod> --container-path=<remote_path> --local-path=<local_path>

**Local Environment:**  
- Operating System: linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: IBM Cloud
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9+IKS", GitCommit:"405ef9ab782f5b51dff56dabe3628585d99afbfa", GitTreeState:"clean", BuildDate:"2019-11-13T21:34:44Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  
-Im just using devspace syn as an alternative way to copy files from one container to my local repo, in lieu of kubectl cp 

/kind bug

**Comment by FabianKramm** [comment]
@jersGH thanks for reporting this issue! Closing the transport means the connection to the pod / container is shutting down for some reason. Are you running the kubernetes cluster the pod is in locally or is it a remote cluster? Does this issue occur on every occasion when you run devspace sync?

**Comment by jersGH** [comment]
The pod that I'm connecting to resides in a different cluster but we are on the same location. This is the second time I noticed the shutting down of sync and were able to save the log this time.

**Comment by jersGH** [comment]
correction with the execution, this is what I actually used -> devspace sync  --download-on-initial-sync --pod=<podname> --container-path=<remote_path> --local-path=<local_path> > logfile 2>&1 &

**Comment by jersGH** [comment]
correction with the execution, this is what I actually used -> devspace sync  --download-on-initial-sync --pod=<podname> --container-path=<remote_path> --local-path=<local_path> > logfile 2>&1 &

**Comment by jersGH** [comment]
@FabianKramm, any insights regarding this issue?

**Comment by FabianKramm** [comment]
@jersGH To be honest I cannot say why the connection is shutting down exactly, but what we could implement is restarting the sync completely if such an error is encountered

**Comment by FabianKramm** [comment]
Should be fixed in v4.3.3
