### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by xinglongjian** [devspace-cloud/devspace#835]
**What happened?**  
[root@learncloudnative quickstart-golang]# devspace dev --debug
[info]   Using kube context 'minikube'
[info]   Using namespace 'default'
[info]   Skip building image 'default'                                     
[info]   Skipping deployment quickstart-golang
[done] √ Port forwarding started on 8080:8080                          
[done] √ Sync started on /root/codespace/quickstart-golang <-> . (Pod: default/quickstart-golang-68c6b5f75c-lrtmq)
[info]   Opening 'http://localhost:8080' as soon as application will be started (timeout: 4m0s)

[error]  Fatal sync error: Sync - connection lost to pod default/quickstart-golang-68c6b5f75c-lrtmq:  command terminated with exit code 139. For more information check .devspace/logs/sync.log

[wait] \ Starting the ui server... (0s)

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- Operating System: linux
- Deployment method:  kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider:minikube
- Kubernetes Version:1.13.4

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@xinglongjian thanks for reporting this issue! Seems like the container encounters an error while running and hence the sync is shut down and fails with this error message.

**Comment by xinglongjian** [comment]
The status of the container in kubernetes is Running. And run px aux command， the result is：

root@quickstart-golang-68c6b5f75c-lrtmq:/go/src/app# ps -aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0   2376   652 ?        Ss   07:04   0:00 /bin/sh -c CompileDaemon -log-prefix=false -color=true -build="go build -o
root          6  0.0  0.0 105004  1976 ?        Sl   07:04   0:00 CompileDaemon -log-prefix=false -color=true -build=go build -o /tmp/my-app
root         89  0.0  0.0 477584  2644 ?        Sl   07:04   0:00 /tmp/my-app
root        195  0.0  0.0   3856  2032 pts/0    Ss   08:22   0:00 bash
root        209  0.0  0.0   7628  1336 pts/0    R+   09:13   0:00 ps -aux

**Comment by FabianKramm** [comment]
@xinglongjian okay thanks for this information! Could you post your devspace.yaml in here?

**Comment by xinglongjian** [comment]
exec `devspace sync` and the same error

**Comment by FabianKramm** [comment]
Should be fixed in v4.3.3
