### ISSUE TITLE
Devspace error with microk8s local cluster

### ISSUE THREAD

**Issue by Jasondeependra** [devspace-cloud/devspace#843]
**What happened?**  
I am using devspace with microk8s cluster in local ubuntu 18.04 machine. When i run command <devspace dev> it throws error:
[fatal]  Unable to create namespace: Post https://127.0.0.1:16443/api/v1/namespaces: x509: certificate signed by unknown authority

**What did you expect to happen instead?**  

Seems like the unsigned certificate causing problem in communicating between devspace cli to microk8s api server.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
I have ubuntu 18.04. You can install microk8s and install devspace cli then run below command
<devspace use context microk8s>
devspace use namespace <anyname>
<devspace dev>

**Local Environment:**  
- Operating System: Ubuntu 18.04
- Deployment method: devspace cli

**Kubernetes Cluster:**  
- Cloud Provider: microk8s 
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", 

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@Jasondeependra thanks for opening this issue! Can you access the cluster via kubectl and create namespaces? Is another command like `devspace enter` or `devspace logs` working for you?

**Comment by Jasondeependra** [comment]
Hi devspace logs also throwing same error. with kubectl it works

**Comment by FabianKramm** [comment]
@Jasondeependra do you have any KUBECONFIG environment variable specified? Do you see the correct kube contexts when you execute `devspace use context`?

**Comment by Jasondeependra** [comment]
@FabianKramm  Thank You. `devspace use context` work fine. But KUBECONFIG seems not configured. Can you please guide me how to configure for microk8s.

**Comment by FabianKramm** [comment]
@Jasondeependra okay thank you! You don't need KUBECONFIG to be configured, but has sometimes caused issues, so I just wanted to check if this might be related to your problem.

**Comment by FabianKramm** [comment]
@Jasondeependra How did you create your kube config from microk8s? I suspect your certificate-authority-data is wrong. Can you `cat ~/.kube/config` and check that the cluster: certificate-authority-data has a correct value? Did you create an alias for `microk8s.kubectl` to `kubectl`?

**Comment by FabianKramm** [comment]
To create a correct kube config for microk8s run `microk8s.kubectl config view --raw > ~/.kube/config`
