### ISSUE TITLE
Question/Feature: render manifests for use in GitOps workflow

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#846]
**Is your feature request related to a problem?**  

I would like to use DevSpace for development, but argocd for deploying production code. Is there a way to generate manifests so that they can pushed for gitops-style workflow?

**Which solution do you suggest?**  

I'm trying to migrate to DevSpace from `skaffold` ... I am basically looking for the equivalent of `skaffold render`.

**Which alternative solutions exist?**  

Not sure, but happy to hear. Deploy production to local cluster then scrape the manifests from the namespace? :)

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Sounds reasonable, we can implement this.

**Comment by shaunc** [comment]
Great -- thanks! ... I'll be happy to try out any branch with this.

**Comment by shaunc** [comment]
BTW -- any idea of schedule? Depending on timeframe, this may become a blocker for us. Its probably unrealistic for us to implement as a whole given everything else we have on our plate and unfamiliarity with the codebase, but given a rough implementation on a branch we will certainly test, and may be able to help debug & patch.

**Comment by FabianKramm** [comment]
@shaunc should be done by the end of next week

**Comment by shaunc** [comment]
Excellent!

**Comment by FabianKramm** [comment]
Implemented in v4.3.5
