### ISSUE TITLE
Don't sync files in subdirectories ignored in .dockerignore

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#852]
**What happened?**  

I have a dockerignore with `**/__pycache__`. I have sync setup containing python packages:
```
 - imageName: django
    localSubPath: ./cranedata
    containerPath: /srv/cranedata
```
When I change a python file, it syncs successfully to the server, but then the `pyc` in `__pycache__` is synced back to the host.
```
{"level":"info","msg":"Upstream - Upload File /data/daily/listeners.py","time":"2020-01-06T12:26:25-05:00"}
{"level":"info","msg":"Upstream - Upload 1 create changes (size 18235)","time":"2020-01-06T12:26:25-05:00"}
{"level":"info","msg":"Upstream - Successfully processed 1 change(s)","time":"2020-01-06T12:26:25-05:00"}
{"level":"info","msg":"Downstream - Download file /data/daily/__pycache__/listeners.cpython-36.pyc, size: 13503","time":"2020-01-06T12:26:35-05:00"}
{"level":"info","msg":"Downstream - Successfully processed 1 change(s)","time":"2020-01-06T12:26:35-05:00"}
```

**What did you expect to happen instead?**  

The pycache contents should not be synced back. Alternatively, if sync settings are meant to override dockerignore, this should be in the doc, and an alternate mechanism to exclude selected paths should be included.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

mac, helm

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! What prevents you from using the `dev.sync.*.excludePaths`? We actually thought about automatically excluding files and folders defined in `.gitignore` and `.dockerignore`, but there are cases, where you want to sync such files.

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! The sync is not meant to exclude paths from the `.dockerignore`, so I think this behavior is correct. The way to exclude such files would be to add them to the `dev.sync.excludePaths` config option. We initially thought about automatically excluding files from .dockerignore or .gitignore, but there seem to be cases where you want to sync such files.

**Comment by shaunc** [comment]
Ah ... ok: in fact I had overlooked `dev.sync.excludePaths`. Thanks, and sorry to bother you!
