### ISSUE TITLE
sync: on-demand sync missing exclude files capability

### ISSUE THREAD

**Issue by dsuievalov** [devspace-cloud/devspace#854]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
If it will be possible, extend on-demand `devspace sync` cli cmd with the missing capabilities that already present in yaml declared sync for dev (https://devspace.cloud/docs/cli/configuration/reference#devsync) like:
-  `excludePaths`
- `downloadExcludePaths`
- `uploadExcludePaths`

**Which alternative solutions exist?**  

Run sync via `devspace dev` spin up procedure.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@dsuievalov thanks for opening this issue! We currently have a flag in `devspace sync` for  `excludePaths`, its `--exclude`, is that not sufficient?

**Comment by dsuievalov** [comment]
@FabianKramm Have rechecked our workflow and I think we will be satisfied with  `--exclude` argument. Sorry for opening and issue instead of clarifying with `devspace sync` cmd.
