### ISSUE TITLE
sync (in devspace dev) should optionally wait for pods to exit the CrashLoopBackoff

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#861]
**Is your feature request related to a problem?**  
"Sync (in devspace dev) should optionally wait for pods to exit the CrashLoopBackoff (or other failed state) instead of crashing the whole dev process (we have several pods that don’t come up without some manual initialization)"

**Which solution do you suggest?**  
Instead of a fatal, DevSpace should print a warning with the pod status (if status != running) and then enter a retry-loop until the pod is running or the user aborts.

**Which alternative solutions exist?**  
Keeping the fatal.

**Additional context**  

Credits to @korbin for suggesting this via Slack.

/kind feature

**Comment by FabianKramm** [comment]
This should actually work already with the new sync restart feature.
