### ISSUE TITLE
feature: inheritance for profiles

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#862]
**Is your feature request related to a problem?**  
"It would be very nice to be able to use multiple profiles (sets of patches) to enable/disable various sets of features"

**Which solution do you suggest?**  
Profile-Inheritance. Adding a config option such as `inheritsFrom/basedOn/uses/parent: PROFILE_NAME` would allow a profile to adopt all patches from another profile. Not sure which name would be best for this config option.

The advantage of inheritance is that is reduces duplicate patches and still makes sure the order is clear (apply inherited patches first (recursively), then the patches of the current profile) => allows overriding patches of parent and is similar to common inheritance patterns.

Compared to multiple active profiles, inheritance also has the advantage that CLI commands like `use profile` would not need to be changed and the order is always clear (behaves similar to class inheritance in object-oriented programming languages).

**Which alternative solutions exist?**  
- Multiple profiles which can be active at the same time => the issue is what is the order of them being applied?
- Multiple profiles with a set of redundant patches => hard to maintain, not great to encourage this in the config (patches are already hard to maintain)

**Additional context**  

Credits to @korbin for suggesting this via Slack.

/kind feature

**Comment by shaunc** [comment]
Excellent idea. Could be called "extends" -- as it is used in various node-related tool config (typescript, eslint,...). My use case is to have "staging" and "production" as similar as possible (different from "dev" and "test"), and to have a "production-monitor" profile that turns on extra metrics and diagnostics, but otherwise is the same as "production". I want my configuration DRY.

**Comment by shaunc** [comment]
An additional "extension of extensions" would be the ability to extend the profile of a dependency (or other external). This would allow factoring out common patterns. Hmm... logically could even allow mixins (multiple inheritance). ... No need to let the great stand in the way of the good though: simple local extension/inheritance would be very useful just by itself.

**Comment by FabianKramm** [comment]
Since this comes up a lot lately, we should implement it!

**Comment by FabianKramm** [comment]
Implemented with #984
