### ISSUE TITLE
Directional sync options between pods

### ISSUE THREAD

**Issue by JJSwanevelder** [devspace-cloud/devspace#871]
**Issue**  
We currently have a server pod and code residing on our local that needs to be synced to the pod/container. Issue currently is that the sync is bi-directional only and we don't necessarily want the containers files to sync with the repository on our local. 

**Proposed solution**
To include in the "devspace sync" directional flags on how the sync takes place:

1. One direction
2. Bidirectional
3. Direction on first sync and direction after first sync.

Above solution would give you more granular control on how sync takes place instead of only having one direction to deal with.

/kind feature

**Comment by FabianKramm** [comment]
@JJSwanevelder thanks for opening this issue! Sounds like a reasonable use case, I think we should implement this.

**Comment by JJSwanevelder** [comment]
@FabianKramm Thank you so much. Will keep an eye out for this.

**Comment by FabianKramm** [comment]
Implemented in v4.4.0
