### ISSUE TITLE
Variable in dependency causes error

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#873]
**What happened?**  

I have a dependency with a variable; when I include it and try to build I get the error:
```
[info]   Start resolving dependencies         
[fatal]  Error deploying dependencies: resolve dependencies recursive: loading config for dependency https://github.com/FactFiber/crane-serverless:/packages/crane-wisdom: Questions in discard logger not supported
```
**What did you expect to happen instead?**  

At the very least, if variables in dependencies are not supported, this should be documented and a better error thrown. However, I would expect that they should be supported.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

The added variable in the devspace.yaml of the dependency is:
```
vars:
- name: GITHUB_SSH_PATH
  default: ./tmp/id_rsa.github
  question: "Enter path in docker context to github private repo key for build"
```
The dependency was correctly 

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

The variable in question is a relative path to a key (in .gitignore) used in a multistage build. I realize now this isn't going to work with a dependency because a key in the parent needs to get into the build context somehow. I guess I could use a custom build that copies the key from an absolute one to a relative one before starting docker build, but I'm all ears for a better solution.

In any case, I presume this bug is independent of the type of variable.

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Yes this seems to be a bug, I'll add the fix for this to the new release that is scheduled for today

**Comment by shaunc** [comment]
@FabianKramm -- this still seems to be happening in `devspace render`?
