### ISSUE TITLE
Community devspace repo/registry/webpage

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#890]
**Is your feature request related to a problem?**  

Just created [FactFiber/devspace-nginx-s3](https://github.com/FactFiber/devspace-nginx-s3),
which is simple service to serve files from a private s3 repository, together with a devspace.yaml to allow it to be used as a dependency.

This is a humble enough offering, but might be useful to someone else. Having other projects "prewrapped" in devspace.yaml so they can be used as dependencies (allowing strict versioning) might be useful.

**Which solution do you suggest?**  

Perhaps create an issue template for submission of services/projects, and a section in the doc website that has a searchable list.

**Which alternative solutions exist?**  

google

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
Thanks for this suggestion, @shaunc! I really like the idea of collecting links to repositories which contain a devspace.yaml and could serve as a dependency for others. 

I will add a docs page for this list and an issue/PR template within the next few days. Great suggestion!

**Comment by shaunc** [comment]
Great --- it would be nice if the template could collect metadata as well if necessary (e.g. especially subpath).

**Comment by LukasGentele** [comment]
@shaunc I am adding this to the new docs right now. Would you mind adding a LICENSE file to your project that is either MIT or Apache-2.0. That would make it easier to endorse it in the docs.

**Comment by shaunc** [comment]
ok -- latest release adds License. Also have adapted https://github.com/FactFiber/devspace-nginx-auth-jwt for devspace
