### ISSUE TITLE
Add `devspace print` to debug patches

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#893]
**Is your feature request related to a problem?**  

Debugging a series of patches seems unnecessarily cumbersome.

**Which solution do you suggest?**  

A new cli command, `devspace print`, which prints the configuration for the current or given profile after all patching and variable substitution. Optionally, could merge configuration from dependencies.

**Which alternative solutions exist?**  

Figuring out what you did wrong by staring at your code & the error messages.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@shaunc you can see the patched configuration in the UI under config, but we could also think about an additional command that just prints the loaded configuration.

**Comment by shaunc** [comment]
Ah -- forgot about it in the UI. I found this feature helpful in serverless. I don't know if the UI even comes up if you have made a big enough blunder? :) But `print` could just deal with substitution so could be quite robust even if you aren't making sense.

**Comment by shaunc** [comment]
(Could eventually be combine with other config management... lint? diff?)

**Comment by FabianKramm** [comment]
Yes sounds good, I think we can do this

**Comment by jerlam06** [comment]
The print command was implemented!

**Comment by shaunc** [comment]
Thanks!
