### ISSUE TITLE
Sync problem connection lost to pod with exit code 139

### ISSUE THREAD

**Issue by irfani** [devspace-cloud/devspace#897]
**What happened?**  
Just upgraded to devspace v4.4.0 and then I have the sync problem. 

sync.log :
```
{"level":"error","msg":"Sync Error on D:\Dev\framework: Sync - connection lost to pod dev/app-0: command terminated with exit code 139","time":"2020-01-24T09:43:55+07:00"}
{"level":"info","msg":"Sync stopped","time":"2020-01-24T09:43:55+07:00"}
```

**What did you expect to happen instead?**  
Sync my local files to pod successfully

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- Operating System: windows
- Deployment method:kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google

**Anything else we need to know?**  
The issue was solved when I switch it back to v4.3.5

/kind bug

**Comment by FabianKramm** [comment]
@irfani thanks for opening this issue! Is there any way that we can reproduce this issue? Is it only not working for a certain image or for every image? Is it working with a local cluster? Any configuration I could test with?

**Comment by irfani** [comment]
I am using alpine based image. Just tried using another image php:7.1-apache-stretch, and I still got the same sync problem.

**Comment by FabianKramm** [comment]
@irfani thanks for the additional information! It works for me with both images, so I think this might be cluster related. You mentioned you are using google cloud provider, could you tell us which GKE Kubernetes version you are using?

**Comment by Lennix** [comment]
I'm having the same issue since 4.4.0. I'm running my own cluster with k8s version 1.13.12.

This is my devspace.yaml:

`version: v1beta6
images:
  default:
    image: myregistry/image
    createPullSecret: false
deployments:
  - name: ballance
    helm:
      componentChart: true
      values:
        containers:
          - image: myregistry/image
            name: default
        ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
          rules:
            - host: xxx
          tls: "false"
        service:
          ports:
            - port: 80
      v2: true
dev:
  ports:
    - imageName: default
      forward:
        - port: 8081
          remotePort: 80
  sync:
    - imageName: default
      localSubPath: ./
      containerPath: /var/app
      downloadExcludePaths:
        - var/
        - public/
      uploadExcludePaths:
        - Dockerfile
        - .devspace/
        - chart/
  autoReload:
    deployments:
      - ballance
    images:
      - default
  interactive:
    defaultEnabled: true
`


Please go ahead if you need more information.

**Comment by irfani** [comment]
Hi Fabian, I am using K8s 1.14.8-gke.12.
Here is my devspace.yml
version: v1beta6
images:
  default:
    image: dscr.io/${DEVSPACE_USERNAME}/app
deployments:
- name: database
  helm:
    componentChart: true
    values:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:11.2
        volumeMounts:
        - containerPath: /var/lib/postgresql/data/pgdata
          volume:
            name: postgres-data
            subPath: /postgres
      service:
        name: postgres
        ports:
        - port: 5432
      volumes:
      - name: postgres-data
        size: 5Gi
- name: app
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/app
        stdin: true
        tty: true
        volumeMounts:
        - containerPath: /root/.gradle
          volume:
            name: data
            subPath: /gradle
        - containerPath: /tmp/axelor
          volume:
            name: data
            subPath: /tmp
      service:
        ports:
        - port: 8080
      volumes:
      - name: data
        size: 5Gi
dev:
  ports:
  - imageName: default
    forward:
    - port: 8080
    - port: 5005
  sync:
  - imageName: default
    excludePaths:
    - Dockerfile
    - .devspace
    - chart
    - bin
    - out
    - .gradle
    - .vscode
    - .idea
    - .settings
    - .project
    - .dockerignore
    - .git
    - devspace.yaml
---
irfani

**Comment by FabianKramm** [comment]
@irfani @Lennix thanks for the information! I just tested and it works for me with gke1.14.8 and gke1.13, the only error that looked somewhat similar that I encountered was a `Sync - connection lost to pod test2/test:  command terminated with exit code 137` when I tried to synchronize the root folder `/`. However, you are probably not trying to sync the root directory are you? Is the `devspace sync` command working for you? Could you try to use the quickstart example (https://github.com/devspace-cloud/devspace/tree/master/examples/quickstart) and check if that is working for you?

**Comment by irfani** [comment]
Hi @FabianKramm  Now it works after upgrade to v 4.5. Thanks.
