### ISSUE TITLE
problem with variables?

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#905]
**What happened?**  

Trying to understand what was happening with variables, wrt to https://github.com/devspace-cloud/devspace/issues/904, I created a new configuration:
```
version: v1beta6
vars:
- name: FOO
  source: all
  question: foo?
  default: xxx

hooks:
  - command: echo
    args:
      - $FOO
    when:
      before:
        images: all
```
And tried to test:
```
% devspace print

-------------------

Vars:
[info]   No vars found

-------------------

Loaded path: /Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/test/devspace.yaml

-------------------

version: v1beta6
dev: {}
hooks:
- command: echo
  args:
  - $FOO
  when:
    before:
      images: all

% devspace list vars
[info]   No variables found
```

**What did you expect to happen instead?**  

I expected the variable FOO to be listed & substituted into hook ... also expected to be asked a value for it as I have a question defined.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Perhaps something screwy has happened with my devspace installation, but if not the above snippet should be sufficient.

**Local Environment:**  
- Operating System:  mac
- Deployment method: n.a.

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

```
% devspace --version
devspace version 4.5.0
```

/kind bug

**Comment by LukasGentele** [comment]
@shaunc Thanks for reporting this. One questions to better reproduce this: Did you set $FOO as environment variable in your terminal before running devspace or not? 

If `source: env`, DevSpace should use either the environment variable or the value of `default` without asking a question if the environment variable is not defined.

However, as you defined `source: all` (which is also the default option if source is not specified), DevSpace should ask the question only if the environment variable is not defined (= empty string). 

This was the intended behavior when we introduced this feature and that is also what is currently documented. We might have accidentally changed the behavior as part of refactoring.

**Comment by shaunc** [comment]
Introducing in the environment makes no difference.
```
% FOO=bar devspace print       

-------------------

Vars:
[info]   No vars found

-------------------

Loaded path: /Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/foo/devspace.yaml

-------------------

version: v1beta6
dev: {}
hooks:
- command: echo
  args:
  - $FOO
  when:
    before:
      images: all
```
In fact even an explicit set seems to make no difference:
```
% devspace set var FOO=barbarous && devspace print
[done] √ Successfully changed variables

-------------------

Vars:
[info]   No vars found

-------------------

Loaded path: /Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/foo/devspace.yaml

-------------------

version: v1beta6
dev: {}
hooks:
- command: echo
  args:
  - $FOO
  when:
    before:
      images: all
```
Though it does have some effect:
```
% cat .devspace/generated.yaml 
vars:
  FOO: barbarous
profiles:
  "":
    lastContext:
      namespace: crane-web
      context: local
```
I would suspect that something has been recently broken... I think variables were better-working previously. If you can't reproduce I'll reinstall and try again....

**Comment by FabianKramm** [comment]
@shaunc the syntax for variables is `${FOO}` not `$FOO`, I guess this is the problem

**Comment by shaunc** [comment]
Ah -- sorry about that. :( ... I guess I was led into complacency by the report of "no vars" at top of print: I didn't know it was dependent on actual use of variable.
