### ISSUE TITLE
Cannot manage dependent deployments 

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#906]
**What happened?**  

Deployments of dependencies do deploy, but cannot be listed or purged from main project that deployed them.

**What did you expect to happen instead?**  

I should be able to manage deployments (& images, etc) of dependencies as well as those declared directly in devspace.yaml

**How can we reproduce the bug?** (as minimally and precisely as possible)  

In ./foo/devspace.yaml:
```
version: v1beta6
dependencies:
- source:
    path: ./bar
```
In ./foo/bar/devspace.yaml:
```
version: v1beta6
deployments:
- name: bar
  helm:
    componentChart: true
    values:
      ingress:
        rules:
        - host: localhost
          serviceName: dummy
          servicePort: 80
```
I can deploy, but not list or delete the ingress deployed as "bar":
```
 % devspace deploy
[info]   Using kube context 'local'
[info]   Using namespace 'crane-web'
[info]   Start resolving dependencies
[done] √ Resolved 1 dependencies
[info]   To display the complete dependency deployment run with the '--verbose-dependencies' flag
[done] √ Deployed dependency /Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/foo/bar                    
[done] √ Successfully deployed 1 dependencies                                                                              
[done] √ Successfully deployed!
         
Run: 
- `devspace open` to create an ingress for the app and open it in the browser 
- `devspace enter` to open a shell into the container 
- `devspace logs` to show the container logs
- `devspace analyze` to analyze the space for potential issues

% devspace list deployments 
[info]   Using kube context 'local'
[info]   Using namespace 'crane-web'

 NAME   TYPE   DEPLOY   STATUS  
 No entries found

% kubectl get ingress
NAME               HOSTS               ADDRESS   PORTS   AGE
bar                localhost                     80      22s
django             dev.cranedata.com             80      2d16h
nginx-s3-ingress   dev.cranedata.com             80      9d

% devspace purge -d bar
[info]   Using kube context 'local'
[info]   Using namespace 'crane-web'

% kubectl get ingress       
NAME               HOSTS               ADDRESS   PORTS   AGE
bar                localhost                     80      36s
django             dev.cranedata.com             80      2d16h
nginx-s3-ingress   dev.cranedata.com             80      9d
```

**Local Environment:**  
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: local
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Yes you are correct, dependencies can currently only be deleted via `devspace purge --dependencies`, however not individually. We could add a flag for deleting them individually and also listing them, but if we dot that we should also add a flag to deploy them individually as well.

**Comment by shaunc** [comment]
For the moment, I am managing dependencies by deploying them separately using a separate bash shell and fiddling with them there :( ... so yes: the current setup seems ok for integrating relatively static dependencies. It doesn't seemed well designed if you are "co-developing" various parts together.

Support for purging, listing, deploying would be great.

Perhaps further down the line you could consider "first class dependency integration" -- dependency hooks, commands, dev setup to merge with current configuration (just that build context would be different). You might want to control that with a flag ("merge: true" -- in dependency inclusion), and could even allow specification of patches to the dependency (primarily in dependency inclusion, indirectly, perhaps, via profile patching in a patch to dependency inclusion).

**Comment by FabianKramm** [comment]
@shaunc devspace v4.5.1 adds support to individually deploy, render & delete dependencies via the new `--dependency` flag

**Comment by shaunc** [comment]
Thank you for that. I don't know if you're interested in dependencies that merge devspace.yaml ("first class dependency integration"), and if so, whether you want another issue to track it? (Otherwise, can close.)

**Comment by FabianKramm** [comment]
@shaunc yes I think a separate issue would be good for this. However, I'm not completely sure if I understand the "first class dependency integration" correctly: you basically want to merge the dependent configs into the current one?  

While I think this would open up new possibilities in terms of flexibility this could make the relationship between them also more brittle, especially with patches that could try to patch things that suddenly do not exist anymore and duplicate deployment names / image names etc. . However, let's take this discussion to a new issue!
