### ISSUE TITLE
devspace sync throws connection lost error

### ISSUE THREAD

**Issue by ravening** [devspace-cloud/devspace#915]
**What happened?**  
Running `devspace sync` command throws connection lost error and repeats the same error forever

**What did you expect to happen instead?**  
Expected devspace to sync the files between local path and the container running in the space

**How can we reproduce the bug?** (as minimally and precisely as possible)  
create a deployment using `devspace deploy`
Now start the development mode using `devspace dev`
Open a new terminal tab, cd to project directory and run `devspace sync` command. You will see below error

```
$ devspace sync
[info]   Using kube context 'devspace-demo'
[info]   Using namespace 'demo'
[info]   Start syncing
[done] √ Sync started on /Users/\<\>/Documents/github/Devspace-demo <-> . (Pod: demo/demo-greetings-7b9f7db69d-ccgns)
[error]  Sync Error on /Users/\<\>/Documents/github/Devspace-demo : Sync - connection lost to pod demo/demo-greetings-7b9f7db69d-ccgns: Cannot sync the root directory command terminated with exit code 1
[info]   Sync stopped
[info]   Restarting sync...
[info]   Start syncing
[done] √ Sync started on /Users/\<\>/Documents/github/Devspace-demo  <-> . (Pod: demo/demo-greetings-7b9f7db69d-ccgns)
[error]  Sync Error on /Users/\<\>/Documents/github/Devspace-demo : Sync - connection lost to pod demo/demo-greetings-7b9f7db69d-ccgns: Cannot sync the root directory command terminated with exit code 1
[info]   Sync stopped
[info]   Restarting sync...
[info]   Start syncing
[done] √ Sync started on /Users/\<\>/Documents/github/Devspace-demo  <-> . (Pod: demo/demo-greetings-7b9f7db69d-ccgns)
[error]  Sync Error on /Users/\<\>/Documents/github/Devspace-demo : Sync - connection lost to pod demo/demo-greetings-7b9f7db69d-ccgns: Cannot sync the root directory command terminated with exit code 1
```

**Local Environment:**  
- Operating System:  mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider:  other
- Kubernetes Version: [use `kubectl version`]
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@ravening thanks for opening this issue! This is actually expected behaviour, since you are trying to sync the complete remote root path `/` with your local folder. If this is desired, you can add a `--container-path /` flag, if not add the correct container path you want to synchronize to.
