### ISSUE TITLE
UI couldn't start with --config file

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#935]
**What happened?**  
When running `devspace dev --config=some-path/devspace.yaml` the UI fails to start with this output
```
[warn]   Couldn't start UI server: load raw config: open <current directory>/devspace.yaml: no such file or directory
```
It seems that the UI ignore the config file given as argument

**Local Environment:**  
- Operating System: mac
- Deployment method: helm
- devspace version 4.5.0

**Kubernetes Cluster:**  
- Cloud Provider: local with docker for mac
- Kubernetes Version: 1.16

/kind bug

**Comment by FabianKramm** [comment]
@igoooor thanks for reporting! Yes you are correct, seems like the ui server is ignoring this flag, I'll fix this.
