### ISSUE TITLE
docs: add note about getting build output for multiple builds via --build-sequential flag

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#942]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**
Related commands: `devspace dev` `devspace build`
Would be nice to have a flag to see the output of the `docker build` when building the image because at the moment we only see `[wait] ⠼ Building 1 image... (0s)`
some kind of `--verbose-build` or something

EDIT:
The goal of such option is to be able to debug the build of the docker image in some cases (to know if it's using cache at some steps, or things like that)

/kind feature

**Comment by FabianKramm** [comment]
@igoooor thanks for opening this issue! This actually already exists with the `--build-sequential` flag, where the output of docker will be shown.

**Comment by igoooor** [comment]
Maybe somewhere in the doc or cli help that information could be added :)
Thanks! 👍

**Comment by FabianKramm** [comment]
@igoooor yes that is true! @LukasGentele can you add this to the documentation?
