### ISSUE TITLE
Can't build dependency with image tag including DEVSPACE_GIT_COMMIT

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#947]
**What happened?**  

I have included a dependency:
```
- source:
    git: https://github.com/FactFiber/devspace-nginx-auth-jwt
```
Which configures tags as:
```
    tag: ${DEVSPACE_GIT_COMMIT}-${DEVELOPER}-${DEVSPACE_RANDOM}
```
When I try to deploy, I get the message:
```
[fatal]  Error deploying dependencies: resolve dependencies: resolve dependencies recursive: loading config for dependency https://github.com/FactFiber/devspace-nginx-auth-jwt - profile dev: No git repository found, but predefined var DEVSPACE_GIT_COMMIT is used
```

**What did you expect to happen instead?**  

I expect that, since devspace is loading the dependency from a git repo, it should be able to figure out the commit.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

I believe that the above should allow you to recreate.

**Local Environment:**  
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: na
- Kubernetes Version: na

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! This should be fixed with #948
