### ISSUE TITLE
dev.open opens last url multiple times

### ISSUE THREAD

**Issue by chasebolt** [devspace-cloud/devspace#952]
**What happened?**  
I have multiple urls defined for `dev.open` and when running `devspace dev` it opens the last url defined N times (N being the amount of urls defined)

**What did you expect to happen instead?**  
To open all urls defined

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Define two urls urls and it will open the last one twice.
```yaml
dev:
  open:
    - url: http://google.com
    - url: http://microsoft.com
```

**Local Environment:**  
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
```
╰─$ devspace --version
devspace version 4.5.3
```

/kind bug

**Comment by FabianKramm** [comment]
@chasebolt thanks for reporting! Yes that is true, I'll fix this.
