### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Ucandoit** [devspace-cloud/devspace#961]
When I use the commande `devspace use namespace`, I got the following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x1d4cd47]

goroutine 1 [running]:
github.com/devspace-cloud/devspace/cmd/use.(*namespaceCmd).RunUseNamespace(0xc00135235b, 0x2a127a0, 0x412f590, 0xc001367b80, 0x412f590, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/runners/2.165.2/work/devspace/devspace/cmd/use/namespace.go:50 +0xb7
github.com/devspace-cloud/devspace/cmd/use.newNamespaceCmd.func1(0xc001367b80, 0x412f590, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/runners/2.165.2/work/devspace/devspace/cmd/use/namespace.go:36 +0x64
github.com/spf13/cobra.(*Command).execute(0xc001367b80, 0x412f590, 0x0, 0x0, 0xc001367b80, 0x412f590)
        /Users/runner/runners/2.165.2/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc001342000, 0x412f590, 0xc001342000, 0x0)
        /Users/runner/runners/2.165.2/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/runners/2.165.2/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:864
github.com/devspace-cloud/devspace/cmd.Execute()
        /Users/runner/runners/2.165.2/work/devspace/devspace/cmd/root.go:70 +0xbd
main.main()
        /Users/runner/runners/2.165.2/work/devspace/devspace/main.go:17 +0x3e

OS : Window Subsystem Linux

/kind bug

**Comment by FabianKramm** [comment]
@Ucandoit thanks for opening this issue! I'll fix this tomorrow, but this panic only occurs if the kube config cannot be loaded, so please make sure you have a valid kube config and `kubectl` works for you.
