### ISSUE TITLE
feature: profile preview

### ISSUE THREAD

**Issue by tomasc** [devspace-cloud/devspace#963]
**Is your feature request related to a problem?**  
no

**Which solution do you suggest?**  
Functionality to the CLI command that prints out the config file for a specified profile. It would help to make sure the patch/replace instructions I write in the profile have the desired effect.

**Which alternative solutions exist?**  
Perhaps looking into the applied config through the UI?

**Additional context**  
N/A

/kind feature

**Comment by LukasGentele** [comment]
We actually added the command `devspace print` recently which prints the config after profiles are applied and config vars are filled in. You can specify the global flag `-p / --profile` to print the config using a certain profile: `devspace print -p my-profile` 

Does that solve your feature request or is there anything else missing?

https://github.com/devspace-cloud/devspace/releases/tag/v4.5.0

**Comment by tomasc** [comment]
Oh fantastic, I must have missed it.
Thanks for such a prompt response, and for devspace itself — I am new to it and so far really enjoy using it.
