### ISSUE TITLE
Tag the built docker images with both the configured tag and "latest"

### ISSUE THREAD

**Issue by zadigus** [devspace-cloud/devspace#972]
**Is your feature request related to a problem?**  
In my case, it's not a big issue, I have a work-around. I would like to use in the devspace commands some of the docker images I've built because they run k8s jobs that base on built images. Because I use the random tag in development, it's pretty difficult to provide the corresponding k8s manifests with the relevant docker image tags in that command. Therefore I think that having a way to **additionally** tagging the built images with some tag of my choice (e.g. "latest") would help because I could just use that tag in my command. But I can imagine there are many other use cases where such a functionality would help. 

**Which solution do you suggest?**  
Add a new flag to allow additional flagging.

**Which alternative solutions exist?**  
Run the `devspace build --tag latest` after having run `devspace build` a first time.

/kind feature

**Comment by igoooor** [comment]
I had the same issue as well, would be good to have indeed.

**Comment by FabianKramm** [comment]
@zadigus thanks for opening this issue! Yes we should do that

**Comment by LukasGentele** [comment]
Instead of `images.[name].tag`, we could add `images.[name].tags` which could be an array of tag schemata. That would be most flexible and very easy to automatically migrate existing configs.

**Comment by FabianKramm** [comment]
Implemented with #983
