### ISSUE TITLE
devspace render: still can't read variables

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#975]
**What happened?**  

After adding a variable to the configuration:
```
% devspace render
[fatal]  Questions in discard logger not supported
```

**What did you expect to happen instead?**  

Question for new variable value.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Should be simple -- will post example if you want.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! It should work if you set the `--show-logs` flag, otherwise we prevent devspace from writing anything other than the rendered manifests to stdout.

**Comment by shaunc** [comment]
Thats fair -- but how about a better error? :)

**Comment by shaunc** [comment]
(Also, couldn't it ask the question on stderr?)

**Comment by FabianKramm** [comment]
@shaunc yes I agree the error message is not optimal, we should enhance this.

**Comment by shaunc** [comment]
Hmm... well I guess just failing with a better error (that mentions `--show-logs`) would be ok. If you were to implement questions via stderr (which for interactive use is still fine, IMO), then for scripting purposes you would need a `--non-interactive` option or similar... which wouldn't be such a bad idea in general, but might understandably seem like overkill for this particular problem.

**Comment by shaunc** [comment]
Great!
