### ISSUE TITLE
Kaniko builds do not respect "chown" commands

### ISSUE THREAD

**Issue by alexandrefilgueira** [devspace-cloud/devspace#982]
**What happened?**  
I'm building a non-root container and one of the steps of my Dockerfile is to change the ownership where my app is placed within the container. For that, I'm using the "chown" command

`RUN chown 1000:1000 -R ${APP_DIR}`

When checking the logs from kaniko and if I even do a "ls" before and after this "chown" command, I see the change is there, but when the image runs, the ownership is root.

The same Dockerfile with kaniko building the image in our CI/CD without devspace doesn't show this problem.

I've tested modifying devspace code to use the latest kaniko release, but the problem persist.

**What did you expect to happen instead?**  
The ownership configured with "chown" in the Dockerfile should be the same when the image is running.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- use kaniko as builder
- Make a folder and apply the chown command in the Dockerfile
- Run "devspace dev"
- Go inside the container and check the file ownership

**Local Environment:**  
- DevSpace Version: 4.5.4
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: none - minikube
- Kubernetes Version: v1.13.12

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@alexandrefilgueira thanks for opening this issue! I'll take a look into this

**Comment by FabianKramm** [comment]
@alexandrefilgueira after some investigation this might be caused by the `--snapshotMode=time` flag we set by default (because it speeds up the kaniko build by large factors). Could you try to disable it via `images.*.build.kaniko.snapshotMode` to `full` (which is the kaniko default) and see if the problem persists?

**Comment by alexandrefilgueira** [comment]
@FabianKramm Yep, that was it, I though it was running as full by default. If it is running with time as default the documentation has a typo.
Thanks for the help
