### ISSUE TITLE
Programming API to integrate with a k8s client

### ISSUE THREAD

**Issue by adibrastegarnia** [devspace-cloud/devspace#986]
Hi
I have a quick question. I am wondering if there is a programming API that can be used to integate devspace with a golang k8s client?

**Comment by LukasGentele** [comment]
Hi @adibrastegarnia! We're shipping the golang client as part of DevSpace, so it's a dependency at the moment. What are you trying to achieve? Trying to understand better what exactly your question and your use case is.

**Comment by adibrastegarnia** [comment]
@LukasGentele 
Thanks for your quick response. We have a test framework that uses k8s golang client API to deploy our systems, add applications, simulators, etc. We provide a command line interface that developers use to add, remove k8s resources and interact with our cluster. The problem we are trying to solve is hot reloading. We would like add a set of commands to our framework to perform hot reloading for our deployments.  to reduce development time. Not sure we can achieve the goal using the client that you are talking about. If you can give me some pointers about that client then that would be great or any other suggestions

**Comment by FabianKramm** [comment]
@adibrastegarnia you can just import the relevant DevSpace packages into your testframework like you would do with any other golang libraries, like we do with client-go etc. The hot reloading functionality lies in the `https://github.com/devspace-cloud/devspace/tree/master/pkg/devspace/sync` package so you'll need definitely this and probably also the `https://github.com/devspace-cloud/devspace/tree/master/pkg/devspace/services`.

**Comment by adibrastegarnia** [comment]
@FabianKramm 
Thanks for the pointers. Will take a look and try it. Will close the issue for now.

**Comment by adibrastegarnia** [comment]
@FabianKramm 
BTW, I forgot to ask a question. Does hot reloading work for go programs? When there is a change in a go file how do you handle it in k8s? Do you restart the pod?

**Comment by FabianKramm** [comment]
@adibrastegarnia yes you have to restart the process (and build process for compiled languages like golang) but there are different possibilities to do that:
- Set the image entrypoint to something like `sleep xxx` and `devspace enter` into the pod and always restart the command manually
- Use something like `nodemon` as entrypoint that detects file changes and restarts the process automatically
- Use a persistent volume & kill the pod / main process after each change (via dev.sync.onUpload.execRemote`) and let kubernetes do the restarting for you

**Comment by adibrastegarnia** [comment]
@FabianKramm 
Good to know thanks for the info. Let me see how it goes.
