### ISSUE TITLE
devspace use space prompts for encryption key after devspace login

### ISSUE THREAD

**Issue by tomasc** [devspace-cloud/devspace#991]
**What happened?**  
In my CircleCI pipeline:
```
#!/bin/bash -eo pipefail
devspace login --key=$DEVSPACE_ACCESS_KEY
[done] √ Successfully logged into app.devspace.cloud
[done] √ Successfully logged into docker registry dscr.io
[info]   You can now use dscr.io/tomasc/* to deploy private docker images
[info]   Successful logged into app.devspace.cloud
CircleCI received exit code 0
```

```
#!/bin/bash -eo pipefail
devspace use space production
                                             (0s)
? Please enter your encryption key for cluster my-cluster

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**What did you expect to happen instead?**  
The script should set the space without prompting for encryption key.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: 4.5.4
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud + DigitalOcean
- Kubernetes Version: 1.17.3

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@tomasc thanks for reporting! Actually, the access key and cluster encryption key are two different things:
- The access key is needed to access the DevSpace Cloud API (on prem & hosted)
- The cluster encryption key is DevSpace Cloud hosted specific and only needed for decrypting the cluster service account token saved in our database (hosted only)

Unfortunately there is currently no command to set the cluster encryption key, so I think the only workaround would be to pass the key via stdin to the `devspace use space production` command.

**Comment by tomasc** [comment]
Thanks @FabianKramm.

Just to make sure: is this the best way to deploy using devspace cloud via CI (CircleCI) (and the possibility of the cluster encryption key is just not there yet), or is there another way that I missed?

**Comment by tomasc** [comment]
BTW passing it via stdin like this did the trick:

```
echo $DEVSPACE_CLOUD_ENCRYPTION_KEY >> devspace use space production
```

**Comment by LukasGentele** [comment]
I will add this to the documentation for now but we should definitely add a flag for this, @FabianKramm

**Comment by LukasGentele** [comment]
There is a new command to solve this: `devspace set encryptionkey` -  for more details and all available args and flags, please refer to this docs page: https://devspace.sh/cli/docs/commands/devspace_set_encryptionkey

Closing this. Thanks again for reporting this issue.
